---
title: "SCENIC"
output: html_document
date: "2024-08-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/u/project/xyang123/jshin/medial_septum_sct")

library(Seurat)
library(tidyverse)
library(magrittr)
library(SCENIC)
library(SingleCellExperiment)
library(SCopeLoomR)
```

```{r}
##load Seurat object
seurat <- readRDS("/u/scratch/j/jshin/medial_septum_sct/Saves/For_Figures_new.rds")
samples_to_remove <- c("XY-TriSeptum-12", "XY-TriSeptum-24", "XY-TriSeptum-2")
seurat <- subset(seurat, data.sampleName %in% samples_to_remove, invert = TRUE)
seurat <- subset(seurat, class_simplify %in% c("Other", "Unknown"), invert = TRUE)

Idents(seurat) <- 'class_simplify'
DefaultAssay(seurat) <- 'RNA'
```

```{r}
##filter genes 
exprMat <- seurat@assays$RNA@data
cellInfo <- seurat@meta.data %>% dplyr::select(data.sampleName, nCount_RNA, nFeature_RNA, Genotype, Gonad, SexChrom, Trisomy, class_simplify, subclass_simplify, cell.type)

loci1 <- which(rowSums(exprMat) > 1*.01*ncol(exprMat))
exprMat_filter <- exprMat[loci1, ]
```

```{r}
add_cell_annotation <- function(loom, cellAnnotation)
{
  cellAnnotation <- data.frame(cellAnnotation)
  if(any(c("nGene", "nUMI") %in% colnames(cellAnnotation)))
  {
    warning("Columns 'nGene' and 'nUMI' will not be added as annotations to the loom file.")
    cellAnnotation <- cellAnnotation[,colnames(cellAnnotation) != "nGene", drop=FALSE]
    cellAnnotation <- cellAnnotation[,colnames(cellAnnotation) != "nUMI", drop=FALSE]
  }
  
  if(ncol(cellAnnotation)<=0) stop("The cell annotation contains no columns")
  if(!all(get_cell_ids(loom) %in% rownames(cellAnnotation))) stop("Cell IDs are missing in the annotation")
  
  cellAnnotation <- cellAnnotation[get_cell_ids(loom),,drop=FALSE]
  # Add annotation
  for(cn in colnames(cellAnnotation))
  {
    add_col_attr(loom=loom, key=cn, value=cellAnnotation[,cn])
  }
  
  invisible(loom)
}

loom <- build_loom("/u/scratch/j/jshin/medial_septum_sct/Saves/network/SCENIC/loom/seurat_filteredQC.loom", dgem=exprMat_filter)
loom <- add_cell_annotation(loom, cellInfo)
close_loom(loom)
```

