---
title: "DEG_MAST"
output: html_document
date: "2024-01-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/scratch/old-scratch-julianas/medial_septum_sct") ##change later

library(ggplot2)
#library(GGally)
#library(GSEABase)
library(limma)
library(reshape2)
library(data.table)
library(knitr)
library(stringr)
#library(NMF)
library(RColorBrewer)
library(MAST)
library(Seurat)
library(scuttle)
library(muscat)
library(magrittr)
library(scater)
library(rsvd)
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
```

```{r}
seurat <- readRDS("Saves/For_Figures.rds") %>% DietSeurat(counts = TRUE)
samples_to_remove <- c("XY-TriSeptum-12", "XY-TriSeptum-24", "XY-TriSeptum-2")
seurat <- subset(seurat, cell.type == "Unknown", invert = TRUE) %>% subset(., data.sampleName %in% samples_to_remove, invert = TRUE)
seurat$cell.type <- gsub(" ", "_", seurat$cell.type)
```

```{r}
sce <- as.SingleCellExperiment(seurat)
qc <- perCellQCMetrics(sce)
ol <- isOutlier(metric = qc$detected, nmads = 2, log = TRUE)
sce <- sce[, !ol]
sce <- sce[rowSums(counts(sce) > 1) >= 10, ]
sce <- computeLibraryFactors(sce)
sce <- logNormCounts(sce)

counts <- assay(sce, "counts")
logcounts <- assay(sce, "logcounts")
cdat <- colData(sce)
fdat <- data.frame(primerid = rownames(logcounts))

scaRaw <- MAST::FromMatrix(exprsArray = as.matrix(logcounts), cData = cdat, fData = fdat)

set.seed(123)
plotPCA <- function(sca_obj){
    projection <- rsvd::rpca(t(assay(sca_obj)), retx=TRUE, k=4)$x
    colnames(projection)=c("PC1","PC2","PC3","PC4")
    pca <- data.table(projection,  as.data.frame(colData(sca_obj)))
    print(ggpairs(pca, columns=c('PC1', 'PC2', 'PC3', 'libSize', 'PercentToHuman', 'nGeneOn', 'exonRate'),
            mapping=aes(color=condition), upper=list(continuous='blank')))
    invisible(pca)
}

#plotPCA(scaRaw)
```

https://github.com/kdzimm/PseudoreplicationPaper/blob/master/Type_1_Error/Type%201%20-%20MAST%20RE.Rmd
https://www.bioconductor.org/packages/release/bioc/vignettes/MAST/inst/doc/MAITAnalysis.html#1_Overview


```{r}
sca <- scaRaw
cdr2 <-colSums(assay(sca)>0)
colData(sca)$ngeneson <- scale(cdr2)

colData(sca)$Genotype <- factor(colData(sca)$Genotype, levels = c("XYM", "XYF", "XXM", "XXF", "XYYM", "XYYF", "XXYM", "XXYF"))
colData(sca)$SexChrom <- factor(colData(sca)$SexChrom, levels = c("XY", "XX", "XYY", "XXY"))
colData(sca)$Gonad <- factor(colData(sca)$Gonad, levels = c("Male", "Female"))
colData(sca)$Trisomy <- factor(colData(sca)$Trisomy, levels = c("Trisomy", "Non-Trisomy"))

colData(sca)$Xdose_cont <- plyr::mapvalues(colData(sca)$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(2, 2, 1 ,1)) %>% as.character() %>% as.numeric()
colData(sca)$Ydose_cont <- plyr::mapvalues(colData(sca)$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 1 ,2)) %>% as.character() %>% as.numeric()

colData(sca)$base_SexChrom <- plyr::mapvalues(colData(sca)$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c("XX", "XY", "XY" ,"XY")) %>% factor(levels = c("XY", "XX"))

colData(sca)$addX <- plyr::mapvalues(colData(sca)$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 0, 0)) %>% as.numeric()

colData(sca)$addY <- plyr::mapvalues(colData(sca)$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 0, 0, 1)) %>% as.numeric()

##FCG
for(i in 1:length(allcells)) {
  
  currentcell <- allcells[i]
  subset <- MAST::subset(sca, cell.type == currentcell & SexChrom %in% c("XY", "XX")) 
  colData(subset)$Genotype <- factor(colData(subset)$Genotype, levels = c("XYM", "XYF", "XXM", "XXF"))
  colData(subset)$SexChrom <- factor(colData(subset)$SexChrom, levels = c("XY", "XX"))
  colData(subset)$data.sampleName <- factor(colData(subset)$data.sampleName)
  
  zlmCond <- MAST::zlm(~ ngeneson + Gonad + SexChrom + Gonad:SexChrom + (1 | data.sampleName),
                                            subset, method='glmer',ebayes = F,
                                            strictConvergence = FALSE)
  
  #zlmCond <- MAST::zlm(~ngeneson + Genotype + (1 | orig.ident), subset, 
  #                   method='glmer',ebayes = F, strictConvergence = FALSE)
  
  
  summaryCond <- suppressMessages(MAST::summary(zlmCond, doLRT = 'GonadFemale'))
  
  summaryDt <- summaryCond$datatable
  
  fcHurdle <- merge(summaryDt[summaryDt$contrast == 'GonadFemale' & summaryDt$component == 'logFC', c(1,7,5,6,8)],
                    summaryDt[summaryDt$contrast == 'GonadFemale' & summaryDt$component == 'H', c(1,4)],
                    by = 'primerid')
  
  fcHurdle <- stats::na.omit(as.data.frame(fcHurdle))
  
  ##save results 
  
}


##Complete model
for(i in 1:length(allcells)) {
  
  currentcell <- allcells[i]
  subset <- MAST::subset(sca, cell.type == currentcell) 
  
  zlmCond <- MAST::zlm(~ ngeneson + Gonad + base_SexChrom + addX + addY + (1 | data.sampleName),
                                            subset, method='glmer',ebayes = F,
                                            strictConvergence = FALSE)
  
  # zlmCond <- MAST::zlm(~ngeneson + Genotype + (1 | orig.ident), subset,
  #                   method='glmer',ebayes = F, strictConvergence = FALSE)
  
  
  summaryCond <- suppressMessages(MAST::summary(zlmCond, doLRT = 'GonadFemale'))
  
  summaryDt <- summaryCond$datatable
  
  fcHurdle <- merge(summaryDt[summaryDt$contrast == 'GonadFemale' & summaryDt$component == 'logFC', c(1,7,5,6,8)],
                    summaryDt[summaryDt$contrast == 'GonadFemale' & summaryDt$component == 'H', c(1,4)],
                    by = 'primerid')
  
  fcHurdle <- stats::na.omit(as.data.frame(fcHurdle))
  
  ##saveresults 
  
}

zlmCond <- MAST::zlm(~ ngeneson + Genotype + (1 | data.sampleName),
                                            sca, method='glmer',ebayes = F,
                                            strictConvergence = FALSE)

zlmCond <- MAST::zlm(~ Gonad + SexChrom + Gonad:SexChrom + ngeneson + (1 | orig.ident), sca, 
                     method='glmer',ebayes = F, strictConvergence = FALSE)
```
