---
title: "mashr"
output: html_document
date: "2024-01-19"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/project-xyang123/medial_septum_sct")

library(limma)
library(edgeR)
library(data.table)
library(tidyverse)
library(Seurat)
library(RColorBrewer)
library(grid)
library(gridExtra)
library(SingleCellExperiment)
library(magrittr)
library(readxl)
library(ggpubr)
library(ggplotify)
library(scuttle)
library(Mus.musculus)
library(mashr)
library(str2str)
library(EnhancedVolcano)
library(dplyr)
library(splines)
library(ComplexUpset)
#library(rowr)
library(corrplot)
library(ggplotify)
library(GGally)
library(cowplot)
```

```{r}
data.dir <- "/u/scratch/j/jshin/old-scratch-julianas/medial_septum_sct"
summed_seurat <- readRDS(file.path(data.dir, "Saves/Pseudobulk_sum_sce_to_seurat.RDS"))

##Edit metadata 
allcells <- unique(summed_seurat$cell.type)

summed_seurat$Xdose <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(2, 2, 1 ,1)) %>% factor(levels = c(1, 2))
summed_seurat$Xdose_cont <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(2, 2, 1 ,1)) %>% as.character() %>% as.numeric()
summed_seurat$Ydose <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 1 ,2)) %>% factor(levels = c(0, 1, 2))
summed_seurat$Ydose_cont <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 1 ,2)) %>% as.character() %>% as.numeric()
summed_seurat$base_SexChrom <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c("XX", "XY", "XY", "XY")) %>% factor(levels = c("XY", "XX"))
summed_seurat$addX <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 0, 0)) %>% as.numeric()
summed_seurat$addY <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 0, 0, 1)) %>% as.numeric()

summed_seurat$Gonad <- factor(summed_seurat$Gonad, levels = c("Male", "Female"))
summed_seurat$SexChrom <- factor(summed_seurat$SexChrom, levels = c("XY", "XX", "XYY", "XXY"))
summed_seurat$Genotype <- factor(summed_seurat$Genotype, levels = c("XYM", "XYF", "XXM", "XXF", "XYYM", "XYYF", "XXYM", "XXYF"))
summed_seurat$Trisomy <- factor(summed_seurat$Trisomy, levels = c("Trisomy", "Non-Trisomy"))
```

PSEUDOBULK WITH MASHR ANALYSIS

```{r}
##normative difference 
SE_list <- list()
EffectSize_list <- list()
resultlist_normative <- list()

for (i in 1:length(allcells)) {
  currentcell <- as.character(allcells[i])
  currentsubset <- subset(summed_seurat, cell.type == currentcell)
  
  dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$Genotype)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  keep.exprs <- filterByExpr(dge)
  x <- dge[keep.exprs,,keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
  
  design <- model.matrix(~0 + Genotype, data = currentsubset@meta.data)
    
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  contrasts <- makeContrasts(XXF_vs_XYM = GenotypeXXF - GenotypeXYM,
                             levels = design)
  fit <- contrasts.fit(fit, contrasts)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_normative[["XXF_vs_XYM"]][[currentcell]] <- topTable(fit, n = Inf, coef = "XXF_vs_XYM", confint = TRUE)
  
  SE <- sqrt(fit$s2.post) * fit$stdev.unscaled
  colnames(SE) <- currentcell
  EffectSize <- fit$coefficients
  colnames(EffectSize) <- currentcell
  
  SE_list[[currentcell]] <- SE
  EffectSize_list[[currentcell]] <- EffectSize
}

SE_all <- do.call("cbind_fill", SE_list)
EffectSize_all <- do.call("cbind_fill", EffectSize_list)

data = mash_set_data(as.matrix(EffectSize_all), as.matrix(SE_all))

##cavariance matrices 
U.c = cov_canonical(data)  
m.1by1 = mash_1by1(data)
strong = get_significant_results(m.1by1,0.05)
U.pca = cov_pca(data,5,subset=strong)
U.ed = cov_ed(data, U.pca, subset=strong)

##run mashr
m   = mash(data, c(U.c,U.ed))

##view results 
length(get_significant_results(m))
head(get_significant_results(m, conditions="Neuron"))
barplot(get_estimated_pi(m),las = 2)

PM <- get_pm(m) 
Pval <- get_lfsr(m)

volcano_list <- list()
for(i in 1:ncol(PM)) {
  
  currentcell <- colnames(PM)[i]
  input <- data.frame(PM[, i], Pval[, i])
  colnames(input) <- c("logFC", "adj.P.Val")
  
  volcano_list[[currentcell]] <- EnhancedVolcano(input,
                lab = rownames(input), 
                x = 'logFC',
                y = 'adj.P.Val',
                subtitle = "XXF_vs_XYM",
                pCutoff = 0.05,
                titleLabSize = 14,
                title = currentcell,
                drawConnectors = TRUE
                )
}

save(m, file = file.path(data.dir, "Results/MASHR_DEG/Normative.Rda"))

pdf("Plots/MASHR_DEG/volcano/Normative.pdf", width  = 20, height = 12)
print(ggarrange(plotlist = volcano_list, ncol = 4, nrow = 2))
dev.off()
```

```{r}
##FUNCTIONS

run_mashr <- function(x) {
  
  PM <- list()
  Pval <- list()
  m_list <- list()
  
  for (j in 1:length(x)) {
    
    currentcomparison <- names(x[j])
    
    if(any(unlist(lapply(x[[j]], function(y) all(is.na(y[,'logFC'])))))) {next}
    
    EffectSize_all <- lapply(x[[j]], function(x) x %>% dplyr::select(logFC)) %>%
      do.call("cbind_fill", .)
    SE <- lapply(x[[j]], function(x) x %>% dplyr::select("CI.L", "CI.R"))
    SE <- lapply(SE, function(x) {x[,3] <- (x[,2] - x[,1]) / 3.92;x})
    SE_all <- lapply(SE, function(x) x %>% dplyr::select(V3)) %>%
      do.call("cbind_fill", .)
    
    colnames(EffectSize_all) <- names(x[[j]])
    colnames(SE_all) <- names(x[[j]])
    
    data = mash_set_data(as.matrix(EffectSize_all), as.matrix(SE_all))
    
    ##cavariance matrices 
    U.c = cov_canonical(data)  
    m.1by1 = mash_1by1(data)
    strong = get_significant_results(m.1by1, 0.05)
    
    if(length(strong) < ncol(EffectSize_all)) { 
      m   = mash(data, c(U.c))
      
    } else {
      U.pca = cov_pca(data,5,subset=strong)
      U.ed = cov_ed(data, U.pca, subset=strong)
      
      ##run mashr
      m   = mash(data, c(U.c,U.ed))
    }
    
    m_list[[currentcomparison]] <- m
    PM[[currentcomparison]] <- get_pm(m) 
    Pval[[currentcomparison]] <- get_lfsr(m)
  }
  return(list(PM, Pval, m_list))
}

run_volcano <- function(x, y) {
  
  volcano_list <- list()
  for(i in 1:length(x)) {
    
    currentPM <- x[[i]]
    currentPval <- y[[i]]
    currentcomparison <- names(x[i])
    
    padj <- -log10(currentPval + 1)
    
    
    
    for(j in 1:ncol(currentPM)) {
      
      currentcell <- colnames(currentPM)[j]
      input <- data.frame(currentPM[, j], currentPval[, j])
      colnames(input) <- c("logFC", "adj.P.Val")
      
      volcano_list[[currentcell]][[currentcomparison]] <- EnhancedVolcano(input,
                  lab = rownames(input), 
                  x = 'logFC',
                  y = 'adj.P.Val',
                  subtitle = currentcomparison,
                  pCutoff = 0.05,
                  FCcutoff = 0.3,
                  titleLabSize = 14,
                  title = currentcell,
                  drawConnectors = TRUE
                  )
    }
  }
  return(volcano_list)
}

run_barplot <- function(x, model_name) {
  
  barplot_list <- list()
  for(i in seq_along(x)) {
  currentcomparison <- names(x)[i]
  df <- get_estimated_pi(x[[i]]) %>% as.data.frame() %>%
    tibble::rownames_to_column(var = "covariances") %>%
    dplyr::mutate(covariances = factor(covariances, levels = covariances))
  colnames(df)[2] <- "estimated_pi"

  
  plot <- ggplot(df, aes(x = covariances, y = estimated_pi)) + 
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
    ggtitle(label = paste(model_name, currentcomparison, sep = " - ")) + 
    xlab("covariances") + 
    ylab("Estimated Mixture Proportions")
    
  
  barplot_list[[currentcomparison]] <- plot
  }
  return(barplot_list)
}

run_scatter <- function(x, model_name) {
  
  scatter_list <- list()
  for(i in seq_along(x)) {
    currentcomparison <- names(x)[i]
    df <- x[[i]] %>% as.data.frame()
    colnames(df) <- c("Astrocyte", "Endothelial", "Ependymal", "Intermediate.Progenitor", "Microglia", "Myelinating.Oligodendrocyte", "Neuron", "Oligodendrocyte.Progenitor")
  
    plot <- ggpairs(df, columns = c(1:8), title = paste(model_name, currentcomparison, sep = " - "), 
                    columnLabels = gsub('.', ' ', colnames(df), fixed = T),
                    labeller = label_wrap_gen(10))
    
    scatter_list[[currentcomparison]] <- plot
  }
  return(scatter_list)
}
```

```{r}
##Normative
resultlist_normative <- list()
for (i in 1:length(allcells)) {
  currentcell <- as.character(allcells[i])
  currentsubset <- subset(summed_seurat, cell.type == currentcell)
  
  dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$data.sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  keep.exprs <- filterByExpr(dge)
  dge <- dge[keep.exprs,,keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
    
  design <- model.matrix(~Genotype, data = currentsubset@meta.data)
  #design <- model.matrix(~0 + Genotype, data = currentsubset@meta.data)
    
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  #cont.matrix <- makeContrasts(GenotypeXXF-GenotypeXYM, levels=design)
  #fit <- contrasts.fit(fit, cont.matrix)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  topTable(fit, n = 10)
    
  resultlist_normative[["XXF_vs_XYM"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GenotypeXXF", confint = TRUE)
  #resultlist_normative[["XXF_vs_XYM"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GenotypeXXF - GenotypeXYM", confint = TRUE)
}

mashr_results <- run_mashr(resultlist_normative)
save(mashr_results, file = file.path(data.dir, "Results/MASHR_DEG/Normative.Rda"))

##barplots
plot_list <- run_barplot(mashr_results[[3]], "Normative")
pdf("Plots/MASHR_DEG/barplot/Normative.pdf", width  = 15, height = 5)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 1))
dev.off()

##volcanoplots
plot_list <- run_volcano(mashr_results[[1]], mashr_results[[2]])
plot_list <- unlist(plot_list, recursive = FALSE, use.names = FALSE)

pdf("Plots/MASHR_DEG/volcano/Normative.pdf", width  = 20, height = 12)
print(ggarrange(plotlist = plot_list, ncol = 4, nrow = 2))
dev.off()

##logFC correlation plot
plot_list <- list()
for(i in seq_along(resultlist_normative)) {
  
  deg_list <- resultlist_normative[[i]]
  currentcomparison <- names(resultlist_normative)[i]
  deg_df <- lapply(gonad_list, function(x) { x %>% dplyr::select(logFC)}) %>% do.call("cbind_fill", .)
  colnames(deg_df) <- c("Astrocyte", "Endothelial", "Ependymal", "Intermediate.Progenitor", "Microglia", "Myelinating.Oligodendrocyte", "Neuron", "Oligodendrocyte.Progenitor")
  
  plot <- ggpairs(deg_df, columns = c(1:8), title = paste("FCG", currentcomparison, sep = " - "), 
                    columnLabels = gsub('.', ' ', colnames(deg_df), fixed = T),
                    labeller = label_wrap_gen(10))
    
  plot_list[[currentcomparison]] <- plot
}
plot <- cowplot::plot_grid(ggmatrix_gtable(plot_list[[1]]), nrow = 1, ncol = 1)
ggsave(filename = "Plots/MASHR_DEG/logfc_scatter/Normative_premashr.pdf", plot = plot, width = 10, height = 10)


plot_list <- run_scatter(mashr_results[[1]], "Normative")
pdf("Plots/MASHR_DEG/logfc_scatter/Normative_mashr.pdf", width  = 10, height = 10, onefile = FALSE)
cowplot::plot_grid(ggmatrix_gtable(plot_list[[1]]), nrow = 1, ncol = 1)
dev.off()
```

```{r}
##FCG Model
resultlist_fcg <- list()
for (i in 1:length(allcells)) {
  currentcell <- as.character(allcells[i])
  currentsubset <- subset(summed_seurat, cell.type == currentcell & Genotype %in% c("XYM","XXF","XXM" ,"XYF"))
  currentsubset@meta.data <- currentsubset@meta.data %>%
  dplyr::mutate(Genotype = factor(Genotype, levels = c("XYM","XXF","XXM" ,"XYF")),
                SexChrom = factor(SexChrom, levels = c("XY", "XX")),
                Gonad = factor(Gonad, levels = c("Male", "Female")))
  
  dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$data.sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  keep.exprs <- filterByExpr(dge)
  dge <- dge[keep.exprs,,keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
    
  design <- model.matrix(~Gonad + SexChrom + Gonad:SexChrom, data = currentsubset@meta.data)
    
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_fcg[["Ovary_vs_Testis"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GonadFemale", confint = TRUE, adjust.method = "BH", p.value = 0.05)
  resultlist_fcg[["XX_vs_XY"]][[currentcell]] <- topTable(fit, n = Inf, coef = "SexChromXX", confint = TRUE, adjust.method = "BH", p.value = 0.05)
  resultlist_fcg[["Ovary:SexChromXX"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GonadFemale:SexChromXX", confint = TRUE)
}

mashr_results <- run_mashr(resultlist_fcg)
save(mashr_results, file = file.path(data.dir, "Results/MASHR_DEG/FCG.Rda"))

##barplots
plot_list <- run_barplot(mashr_results[[3]], "FCG")
pdf("Plots/MASHR_DEG/barplot/FCG.pdf", width  = 15, height = 5)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 1))
dev.off()

##volcanoplots
plot_list <- run_volcano(mashr_results[[1]], mashr_results[[2]])
plot_list <- unlist(plot_list, recursive = FALSE, use.names = FALSE)

pdf("Plots/MASHR_DEG/volcano/FCG.pdf", width  = 15, height = 12)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 2))
dev.off()

##logFC correlation plot
plot_list <- list()
for(i in seq_along(resultlist_fcg)) {
  
  deg_list <- resultlist_fcg[[i]]
  currentcomparison <- names(resultlist_fcg)[i]
  deg_df <- lapply(gonad_list, function(x) { x %>% dplyr::select(logFC)}) %>% do.call("cbind_fill", .)
  colnames(deg_df) <- c("Astrocyte", "Endothelial", "Ependymal", "Intermediate.Progenitor", "Microglia", "Myelinating.Oligodendrocyte", "Neuron", "Oligodendrocyte.Progenitor")
  
  plot <- ggpairs(deg_df, columns = c(1:8), title = paste("FCG", currentcomparison, sep = " - "), 
                    columnLabels = gsub('.', ' ', colnames(deg_df), fixed = T),
                    labeller = label_wrap_gen(10))
    
  plot_list[[currentcomparison]] <- plot
}
plot <- cowplot::plot_grid(ggmatrix_gtable(plot_list[[1]]), ggmatrix_gtable(plot_list[[2]]), ggmatrix_gtable(plot_list[[3]]), nrow = 1, ncol = 3)
ggsave(filename = "Plots/MASHR_DEG/logfc_scatter/FCG_premashr.pdf", plot = plot, width = 30, height = 10)

plot_list <- run_scatter(mashr_results[[1]], "FCG")
plot <- cowplot::plot_grid(ggmatrix_gtable(plot_list[[1]]), ggmatrix_gtable(plot_list[[2]]), ggmatrix_gtable(plot_list[[3]]), nrow = 1, ncol = 3)
ggsave(filename = "Plots/MASHR_DEG/logfc_scatter/FCG_mashr.pdf", plot = plot, width = 30, height = 10)

##logFC correlation between terms 
plot_list <- list()
for(i in 1:length(allcells)) {
  
  currentcell <- allcells[i]
  ct_logfc <- lapply(mashr_results[[1]], function(x) {x %>% as.data.frame() %>% dplyr::select(one_of(currentcell))}) %>% 
    do.call("cbind_fill", .)
  colnames(ct_logfc) <- names(mashr_results[[1]])
  
  plot <- ggpairs(ct_logfc, columns = c(1:3), title = paste("FCG", currentcell, sep = " - "), labeller = label_wrap_gen(10))
  plot_list[[currentcell]] <- plot
}
plot <- cowplot::plot_grid(ggmatrix_gtable(plot_list[[1]]), ggmatrix_gtable(plot_list[[2]]), ggmatrix_gtable(plot_list[[3]]), ggmatrix_gtable(plot_list[[4]]),
                           ggmatrix_gtable(plot_list[[5]]), ggmatrix_gtable(plot_list[[6]]), ggmatrix_gtable(plot_list[[7]]), ggmatrix_gtable(plot_list[[8]]), nrow = 2, ncol = 4)
ggsave(filename = "Plots/MASHR_DEG/logfc_scatter/FCG_mashr_ct.pdf", plot = plot, width = 20, height = 10)
```

```{r}
##full model (X and Y dose + gonad)

resultlist_dose <- list()
for (i in 1:length(allcells)) {
  currentcell <- as.character(allcells[i])
  currentsubset <- subset(summed_seurat, cell.type == currentcell)
  
  dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$data.sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  keep.exprs <- filterByExpr(dge)
  dge <- dge[keep.exprs,,keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
    
  design <- model.matrix(~Gonad + Xdose_cont + Ydose_cont, data = currentsubset@meta.data)
    
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_dose[["Ovary_vs_Testis"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GonadFemale", confint = TRUE)
  resultlist_dose[["Xdose"]][[currentcell]] <- topTable(fit, n = Inf, coef = "Xdose_cont", confint = TRUE)
  resultlist_dose[["Ydose"]][[currentcell]] <- topTable(fit, n = Inf, coef = "Ydose_cont", confint = TRUE)
}

mashr_results <- run_mashr(resultlist_dose)
save(mashr_results, file = file.path(data.dir, "Results/MASHR_DEG/Dose.Rda"))

##barplots
plot_list <- run_barplot(mashr_results[[3]], "Dose")
pdf("Plots/MASHR_DEG/barplot/Dose.pdf", width  = 15, height = 5)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 1))
dev.off()

##volcanoplots
plot_list <- run_volcano(mashr_results[[1]], mashr_results[[2]])
plot_list <- unlist(plot_list, recursive = FALSE, use.names = FALSE)

pdf("Plots/MASHR_DEG/volcano/Dose.pdf", width  = 15, height = 12)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 2))
dev.off()

##logFC correlation plot
plot_list <- run_scatter(mashr_results[[1]], "Dose")
plot <- cowplot::plot_grid(ggmatrix_gtable(plot_list[[1]]), ggmatrix_gtable(plot_list[[2]]), ggmatrix_gtable(plot_list[[3]]), nrow = 1, ncol = 3)
ggsave(filename = "Plots/MASHR_DEG/logfc_scatter/Dose_mashr.pdf", plot = plot, width = 30, height = 10)
```

```{r}
##Aneuploidy model
resultlist_aneuploidy <- list()
for (i in 1:length(allcells)) {
  currentcell <- as.character(allcells[i])
  currentsubset <- subset(summed_seurat, cell.type == currentcell)
  
  dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$data.sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  keep.exprs <- filterByExpr(dge)
  dge <- dge[keep.exprs,,keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
  
  design <- model.matrix(~Gonad + base_SexChrom + Trisomy + Gonad:base_SexChrom + Gonad:Trisomy + base_SexChrom:Trisomy, data = currentsubset@meta.data) 
  
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
    
  resultlist_aneuploidy[["Ovary_vs_Testis"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GonadFemale", confint = TRUE)
  resultlist_aneuploidy[["XX_vs_XY"]][[currentcell]] <- topTable(fit, n = Inf, coef = "base_SexChromXX", confint = TRUE)
  resultlist_aneuploidy[["Aneuploidy"]][[currentcell]] <- topTable(fit, n = Inf, coef = "TrisomyNon-Trisomy", confint = TRUE)
  #resultlist_aneuploidy[["Ovary:SexChromXX"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GonadFemale:base_SexChromXX", confint = TRUE)
  #resultlist_aneuploidy[["Ovary:Aneuploidy"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GonadFemale:TrisomyNon-Trisomy", confint = TRUE)
  #resultlist_aneuploidy[["SexChromXX:Aneuploidy"]][[currentcell]] <- topTable(fit, n = Inf, coef = "base_SexChromXX:TrisomyNon-Trisomy", confint = TRUE)
}

mashr_results <- run_mashr(resultlist_aneuploidy)
save(mashr_results, file = file.path(data.dir, "Results/MASHR_DEG/Aneuploidy.Rda"))
    
##barplots
plot_list <- run_barplot(mashr_results[[3]], "Aneuploidy")
pdf("Plots/MASHR_DEG/barplot/Aneuploidy.pdf", width  = 15, height = 5)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 1))
dev.off()

##volcanoplots
plot_list <- run_volcano(mashr_results[[1]], mashr_results[[2]])
plot_list <- unlist(plot_list, recursive = FALSE, use.names = FALSE)

pdf("Plots/MASHR_DEG/volcano/Aneuploidy.pdf", width  = 15, height = 12)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 2))
dev.off()

##logFC correlation plot
plot_list <- run_scatter(mashr_results[[1]], "Aneuploidy")
plot <- cowplot::plot_grid(ggmatrix_gtable(plot_list[[1]]), ggmatrix_gtable(plot_list[[2]]), ggmatrix_gtable(plot_list[[3]]), nrow = 1, ncol = 3)
ggsave(filename = "Plots/MASHR_DEG/logfc_scatter/Aneuploidy_mashr.pdf", plot = plot, width = 30, height = 10)
```

```{r}
##Quadratic Model with splines 
resultlist_quad <- list()
fit_list <- list()
for (i in 1:length(allcells)) {
  currentcell <- as.character(allcells[i])
  currentsubset <- subset(summed_seurat, cell.type == currentcell)
  
  dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$data.sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  keep.exprs <- filterByExpr(dge)
  dge <- dge[keep.exprs,,keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
  
  metadata <- currentsubset@meta.data
  metadata$X <- ns(metadata$Ydose_cont, df = 2)
  
  design <- model.matrix(~Gonad + Xdose_cont + X, data = metadata)
  #design <- model.matrix(~Gonad + Xdose_cont + poly(Ydose_cont, degree=2), data=currentsubset@meta.data)

  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
    
  resultlist_quad[["Ovary_vs_Testis"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GonadFemale", confint = TRUE)
  resultlist_quad[["Xdose"]][[currentcell]] <- topTable(fit, n = Inf, coef = "Xdose_cont", confint = TRUE)
  resultlist_quad[["Ydose"]][[currentcell]] <- topTable(fit, n = Inf, coef = c("X1", "X2"), confint = TRUE)
  #resultlist_quad[["Ydose"]][[currentcell]] <- topTable(fit, n = Inf, coef = "poly(Ydose_cont, degree = 2)1", confint = TRUE)
  #resultlist_quad[["Ydose^2"]][[currentcell]] <- topTable(fit, n = Inf, coef = "poly(Ydose_cont, degree = 2)2", confint = TRUE)
  
  fit_list[[currentcell]] <- fit
  
  #save(resultlist_quad, file = paste0("Data/Derived/Pseudobulk_DEG/Quadratic/", currentcell,".rda"))
}

mashr_results <- run_mashr(resultlist_quad[1:2])

##to-do: figure out how to run mashr with multiple coefficients for Ydose
##use logFC from dose model and adjusted P value from quadratic? 

currentcomparison <- names(resultlist_quad[3])

logfc <- list()
for(i in seq_along(resultlist_dose$Ydose)) {
  ct_logfc <- resultlist_dose$Ydose[[i]] %>% dplyr::select(logFC)
  colnames(ct_logfc) <- names(resultlist_dose$Ydose[i])
  logfc[[i]] <- ct_logfc
}
logfc <- do.call("cbind_fill", logfc)
logfc

SE_list <- lapply(fit_list, function(x) {
  sqrt(x$s2.post) / sqrt(21)
})

SE <- do.call("cbind_fill", SE_list)
colnames(SE) <- names(SE_list)
SE <- SE[match(rownames(logfc), rownames(SE)),]

data = mash_set_data(as.matrix(logfc), as.matrix(SE))
    
##cavariance matrices 
U.c = cov_canonical(data)  
m.1by1 = mash_1by1(data)
strong = get_significant_results(m.1by1, 0.05)

if(length(strong) < ncol(logfc)) { 
  m   = mash(data, c(U.c))
  
} else {
  U.pca = cov_pca(data,5,subset=strong)
  U.ed = cov_ed(data, U.pca, subset=strong)
  
  ##run mashr
  m   = mash(data, c(U.c,U.ed))
  }

mashr_results[[1]][[currentcomparison]] <- get_pm(m)
mashr_results[[2]][[currentcomparison]] <- get_lfsr(m)

plot_list <- run_volcano(mashr_results[[1]], mashr_results[[2]])
plot_list <- unlist(plot_list, recursive = FALSE, use.names = FALSE)

save(mashr_results, file = file.path(data.dir, "Results/MASHR_DEG/Quadratic.Rda"))

pdf("Plots/MASHR_DEG/volcano/Quadratic.pdf", width  = 15, height = 12)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 2))
dev.off()
```

```{r}
##full model (X and Y dose + gonad) - Y dose factor

resultlist_dose_factor <- list()
for (i in 1:length(allcells)) {
  currentcell <- as.character(allcells[i])
  currentsubset <- subset(summed_seurat, cell.type == currentcell)
  
  dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$data.sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  keep.exprs <- filterByExpr(dge)
  dge <- dge[keep.exprs,,keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
    
  design <- model.matrix(~Gonad + Xdose_cont + Ydose, data = currentsubset@meta.data)
    
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_dose_factor[["Ovary_vs_Testis"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GonadFemale", confint = TRUE)
  resultlist_dose_factor[["Xdose"]][[currentcell]] <- topTable(fit, n = Inf, coef = "Xdose_cont", confint = TRUE)
  resultlist_dose_factor[["Ydose1"]][[currentcell]] <- topTable(fit, n = Inf, coef = "Ydose1", confint = TRUE)
  resultlist_dose_factor[["Ydose2"]][[currentcell]] <- topTable(fit, n = Inf, coef = "Ydose2", confint = TRUE)
}

mashr_results <- run_mashr(resultlist_dose_factor)
save(mashr_results, file = file.path(data.dir, "Results/MASHR_DEG/Dose_factor.Rda"))

##barplots
plot_list <- run_barplot(mashr_results[[3]], "Dose_factor")
pdf("Plots/MASHR_DEG/barplot/Dose_factor.pdf", width  = 15, height = 5)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 1))
dev.off()

##volcanoplots
plot_list <- run_volcano(mashr_results[[1]], mashr_results[[2]])
plot_list <- unlist(plot_list, recursive = FALSE, use.names = FALSE)

pdf("Plots/MASHR_DEG/volcano/Dose_factor", width  = 15, height = 12)
print(ggarrange(plotlist = plot_list, ncol = 3, nrow = 2))
dev.off()

##logFC correlation plot
plot_list <- run_scatter(mashr_results[[1]], "Dose_factor")
plot <- cowplot::plot_grid(ggmatrix_gtable(plot_list[[1]]), ggmatrix_gtable(plot_list[[2]]), ggmatrix_gtable(plot_list[[3]]), ggmatrix_gtable(plot_list[[4]]), nrow = 2, ncol = 2)
ggsave(filename = "Plots/MASHR_DEG/logfc_scatter/Dose_factor_mashr.pdf", plot = plot, width = 20, height = 20)
```

```{r}
##full model 

resultlist_full <- list()
for (i in 1:length(allcells)) {
  currentcell <- as.character(allcells[i])
  currentsubset <- subset(summed_seurat, cell.type == currentcell)
  
  dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$data.sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  keep.exprs <- filterByExpr(dge)
  dge <- dge[keep.exprs,,keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
    
  design <- model.matrix(~Gonad + base_SexChrom + addX + addY, data = currentsubset@meta.data)
    
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_full[["Ovary_vs_Testis"]][[currentcell]] <- topTable(fit, n = Inf, coef = "GonadFemale", confint = TRUE)
  resultlist_full[["XX_vs_XY"]][[currentcell]] <- topTable(fit, n = Inf, coef = "base_SexChromXX", confint = TRUE)
  resultlist_full[["X"]][[currentcell]] <- topTable(fit, n = Inf, coef = "addX", confint = TRUE)
  resultlist_full[["Y"]][[currentcell]] <- topTable(fit, n = Inf, coef = "addY", confint = TRUE)
}

mashr_results <- run_mashr(resultlist_full)
save(mashr_results, file = file.path(data.dir, "Results/MASHR_DEG/Full.Rda"))

m <- mashr_results[[3]]

##barplots
plot_list <- run_barplot(mashr_results[[3]], "Full")
pdf("Plots/MASHR_DEG/barplot/Full.pdf", width  = 20, height = 5)
print(ggarrange(plotlist = plot_list, ncol = 4, nrow = 1))
dev.off()

##volcanoplots
plot_list <- run_volcano(mashr_results[[1]], mashr_results[[2]])
plot_list <- unlist(plot_list, recursive = FALSE, use.names = FALSE)

pdf("Plots/MASHR_DEG/volcano/Full.pdf", width  = 20, height = 12)
print(ggarrange(plotlist = plot_list, ncol = 4, nrow = 2))
dev.off()

##logFC correlation plot
plot_list <- run_scatter(mashr_results[[1]], "Full")
plot <- cowplot::plot_grid(ggmatrix_gtable(plot_list[[1]]), ggmatrix_gtable(plot_list[[2]]), ggmatrix_gtable(plot_list[[3]]), ggmatrix_gtable(plot_list[[4]]), nrow = 2, ncol = 2)
ggsave(filename = "Plots/MASHR_DEG/logfc_scatter/Full_mashr.pdf", plot = plot, width = 20, height = 20)
```
