---
title: "Pseudobulk DEG Analysis"
output: html_document
date: "2023-11-08"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/u/project/xyang123/julianas/medial_septum_sct")

library(limma)
library(edgeR)
library(data.table)
library(plyr)
library(dplyr)
library(Seurat)
library(enrichplot)
library(ggplot2)
library(RColorBrewer)
library(grid)
library(gridExtra)
library(SingleCellExperiment)
library(magrittr)
library(stringr)
library(enrichplot)
library(readxl)
library(tidyr)
library(purrr)
library(ggridges)
library(ggpubr)
library(ggplotify)
library(SuperCell)
library(scuttle)
library(Mus.musculus)
```

```{r}
seurat <- readRDS( "~/scratch/medial_septum_sct/Saves/For_Figures.rds") %>% DietSeurat(counts = TRUE)
seurat$cell.type <- gsub(" ", "_", seurat$cell.type)
summed_seurat <- AggregateExpression(seurat,
                              return.seurat = TRUE,
                              group.by = c("data.sampleName", "cell.type"),
                              verbose = TRUE)

##add metadata to pseudobulk count object 
metadata <- seurat@meta.data %>% dplyr::select(data.sampleName, Genotype, Gonad, SexChrom, Dosage, Trisomy)
rownames(metadata) <- NULL
metadata <- unique(metadata)
rownames(metadata) <- metadata$data.sampleName 
metadata <- metadata %>% dplyr::select(-c(data.sampleName, Dosage))

for (meta in names(metadata)) {
  column <- metadata[, meta]
  summed_seurat[[meta]] <- plyr::mapvalues(
    x = summed_seurat$orig.ident,
    from = rownames(metadata),
    to = column %>% unlist(use.names = FALSE))
}

saveRDS(summed_seurat, "~/scratch/medial_septum_sct/Saves/Pseudobulk_seurat.RDS")

####

seurat <- subset(seurat, cell.type == "Unknown", invert = TRUE)
seurat$cell.type <- gsub(" ", "_", seurat$cell.type)
sce <- as.SingleCellExperiment(seurat)
summed <- aggregateAcrossCells(sce, 
                               id = colData(sce)[, c("cell.type", "data.sampleName")])
summed$id <- paste(summed$cell.type, summed$orig.ident, sep = "_")

cols_to_keep <- c("id", "data.sampleName", "Genotype", "cell.type", "Gonad", "SexChrom", "Trisomy", "ncells")
colData(summed) <- colData(summed)[, cols_to_keep]

counts <- counts(summed)
colnames(counts) <- summed$id
metadata <- as.data.frame(colData(summed)) 
rownames(metadata) <- metadata$id
metadata$id <- NULL

summed_seurat <- CreateSeuratObject(counts = counts, meta.data = metadata)

samples_to_remove <- c("XY-TriSeptum-12", "XY-TriSeptum-24", "XY-TriSeptum-2")
summed_seurat <- subset(summed_seurat, data.sampleName %in% samples_to_remove, invert = TRUE)

saveRDS(summed_seurat, "~/scratch/medial_septum_sct/Saves/Pseudobulk_sce_toseurat.RDS")
```

```{r, eval = FALSE}
##Edit metadata 
allcells <- unique(summed_seurat$cell.type)

summed_seurat$Xdose <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(2, 2, 1 ,1)) %>% factor(levels = c(1, 2))
summed_seurat$Xdose_cont <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(2, 2, 1 ,1)) %>% as.character() %>% as.numeric()
summed_seurat$Ydose <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 1 ,2)) %>% factor(levels = c(0, 1, 2))
summed_seurat$Ydose_cont <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 1 ,2)) %>% as.character() %>% as.numeric()
summed_seurat$base_SexChrom <- plyr::mapvalues(summed_seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c("XX", "XY", "XY", "XY")) %>% factor(levels = c("XY", "XX"))

summed_seurat$Gonad <- factor(summed_seurat$Gonad, levels = c("Male", "Female"))
summed_seurat$SexChrom <- factor(summed_seurat$SexChrom, levels = c("XY", "XX", "XYY", "XXY"))
summed_seurat$Genotype <- factor(summed_seurat$Genotype, levels = c("XYM", "XYF", "XXM", "XXF", "XYYM", "XYYF", "XXYM", "XXYF"))
summed_seurat$Trisomy <- factor(summed_seurat$Trisomy, levels = c("Trisomy", "Non-Trisomy"))
```

```{r}
##Subset pseudobulk gene counts 
for (i in 1:length(allcells)) {
  
  currentcell <- as.character(allcells[i])
  counts <- summed_seurat@assays$RNA@counts
  indx <- grepl(currentcell, colnames(counts))
  cell_counts <- counts[, indx]
  colnames(cell_counts) <- gsub(paste0("_", currentcell), "", colnames(cell_counts))
  
  dge0 <- DGEList(cell_counts)
  cell_metadata <- metadata[rownames(metadata) %in% rownames(dge0$samples), ]
  
  dge0$samples <- cbind(dge0$samples, cell_metadata) %>%
    dplyr::mutate(Genotype = factor(Genotype, levels = c("XYM", "XYF", "XXM", "XXF", "XYYM", "XYYF", "XXYM", "XXYF")),
                  Gonad = factor(Gonad, levels = c("Male", "Female")),
                  SexChrom = factor(SexChrom, levels = c("XY", "XX", "XYY", "XXY")),
                  Trisomy = factor(Trisomy, levels = c("Non-Trisomy", "Trisomy")),
                  Xdose = plyr::mapvalues(SexChrom,
                                          from = c("XX", "XXY", "XY", "XYY"),
                                          to = c(2, 2, 1 ,1)) %>% as.character() %>% as.numeric(),
                  Ydose = plyr::mapvalues(SexChrom,
                                          from = c("XX", "XXY", "XY", "XYY"),
                                          to = c(0, 1, 1 ,2)) %>% as.character() %>% as.numeric(),
                  base_SexChrom = plyr::mapvalues(SexChrom,
                                  from = c("XX", "XXY", "XY", "XYY"),
                                  to = c("XX", "XY", "XY", "XY")) %>% factor(levels = c("XY", "XX")))
  
  ##count filtering 
  keep.exprs <- filterByExpr(dge0, group = colnames(cell_counts))
  dge <- dge0[keep.exprs, keep.lib.sizes = FALSE]
  dge <- calcNormFactors(dge)
  
  ##gene annotation
  geneid <- rownames(dge)
  genes <- select(Mus.musculus, keys=geneid, columns=c("SYMBOL", "TXCHROM"),
                   keytype = "SYMBOL")
  genes <- genes[!duplicated(genes$SYMBOL),]
  dge$genes <- genes
  
  ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### #####
  
  ##MD5 plots 
  lcpm <- edgeR::cpm(dge0, log=TRUE)
  group <- dge$samples$Genotype
  gonad <- dge$samples$Gonad
  sexchrom <- dge$samples$SexChrom
  
  col.group <- dge$samples$Genotype
  levels(col.group) <-  brewer.pal(nlevels(col.group), "Set2")
  col.group <- as.character(col.group)
  col.gonad <- dge$samples$Gonad
  levels(col.gonad) <-  brewer.pal(nlevels(col.gonad), "Set1")
  col.gonad <- as.character(col.gonad)
  col.sexchrom <- dge$samples$SexChrom
  levels(col.sexchrom) <-  brewer.pal(nlevels(col.sexchrom), "Dark2")
  col.sexchrom <- as.character(col.sexchrom)
  
  pdf(paste0("Plots/Pseudobulk_DEG/PCA/", currentcell, ".pdf"), width = 12, height = 8)
  par(mfrow=c(2,3))
  
  plotMDS(lcpm, labels=group, col=col.group, dim = c(1,2))
  title(main="A. Genotype")
  plotMDS(lcpm, labels=gonad, col=col.gonad, dim=c(1,2))
  title(main="B. Gonad")
  plotMDS(lcpm, labels=sexchrom, col=col.sexchrom, dim=c(1,2))
  title(main="c. SexChrom")
  
  plotMDS(lcpm, labels=group, col=col.group, dim = c(3,4))
  title(main="A. Genotype")
  plotMDS(lcpm, labels=gonad, col=col.gonad, dim=c(3,4))
  title(main="B. Gonad")
  plotMDS(lcpm, labels=sexchrom, col=col.sexchrom, dim=c(3,4))
  title(main="c. SexChrom")
  
  dev.off()
  
  ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### #####
  
  saveRDS(dge, file = paste0("~/scratch/medial_septum_sct/Data/Derived/Pseudobulk_DEG/DGEList/", currentcell, ".RDS"))

}
```

```{r, eval = FALSE}
##density plots 
cpm <- edgeR::cpm(dge0)
lcpm <- edgeR::cpm(dge0, log = TRUE)
L <- mean(dge0$samples$lib.size) * 1e-6
M <- median(dge0$samples$lib.size) * 1e-6

lcpm.cutoff <- log2(10/M + 2/L)
nsamples <- ncol(dge0)
samplenames <- colnames(dge0)
col <- brewer.pal(nsamples, "Paired")
par(mfrow=c(1,2))
plot(density(lcpm[,1]), col=col[1], lwd=2, ylim=c(0,0.26), las=2, main="", xlab="")
title(main="A. Raw data", xlab="Log-cpm")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
den <- density(lcpm[,i])
lines(den$x, den$y, col=col[i], lwd=2)
}
legend("topright", samplenames, text.col=col, bty="n")

lcpm <- edgeR::cpm(dge, log=TRUE)
plot(density(lcpm[,1]), col=col[1], lwd=2, ylim=c(0,0.26), las=2, main="", xlab="")
title(main="B. Filtered data", xlab="Log-cpm")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
den <- density(lcpm[,i])
lines(den$x, den$y, col=col[i], lwd=2)
}
legend("topright", samplenames, text.col=col, bty="n")

##boxplots 
keep.exprs <- filterByExpr(dge0, group = colnames(cell_counts))
dge2 <- dge0[keep.exprs, keep.lib.sizes = FALSE]

par(mfrow=c(1,2))
lcpm <- edgeR::cpm(dge0, log=TRUE)
boxplot(lcpm, las=2, col=col, main="")
title(main="A. Example: Unnormalised data",ylab="Log-cpm")

dge2 <- calcNormFactors(dge2)  
lcpm <- edgeR::cpm(dge2, log=TRUE)
boxplot(lcpm, las=2, col=col, main="")
title(main="B. Example: Normalised data",ylab="Log-cpm")

##MD5 plots 
lcpm <- edgeR::cpm(dge0, log=TRUE)
group <- dge$samples$Genotype
gonad <- dge$samples$Gonad
sexchrom <- dge$samples$SexChrom

col.group <- dge$samples$Genotype
levels(col.group) <-  brewer.pal(nlevels(col.group), "Set2")
col.group <- as.character(col.group)
col.gonad <- dge$samples$Gonad
levels(col.gonad) <-  brewer.pal(nlevels(col.gonad), "Set1")
col.gonad <- as.character(col.gonad)
col.sexchrom <- dge$samples$SexChrom
levels(col.sexchrom) <-  brewer.pal(nlevels(col.sexchrom), "Dark2")
col.sexchrom <- as.character(col.sexchrom)

pdf(paste0("Plots/Pseudobulk_DEG/PCA/", currentcell, ".pdf"), width = 12, height = 8)
par(mfrow=c(2,3))

plotMDS(lcpm, labels=group, col=col.group, dim = c(1,2))
title(main="A. Genotype")
plotMDS(lcpm, labels=gonad, col=col.gonad, dim=c(1,2))
title(main="B. Gonad")
plotMDS(lcpm, labels=sexchrom, col=col.sexchrom, dim=c(1,2))
title(main="c. SexChrom")

plotMDS(lcpm, labels=group, col=col.group, dim = c(3,4))
title(main="A. Genotype")
plotMDS(lcpm, labels=gonad, col=col.gonad, dim=c(3,4))
title(main="B. Gonad")
plotMDS(lcpm, labels=sexchrom, col=col.sexchrom, dim=c(3,4))
title(main="c. SexChrom")

dev.off()
```

##DEG Testing
```{r}
##final loop 

for (i in 1:length(allcells)) {
  
  currentcell <- as.character(allcells[i])
  dge <- readRDS(paste0("~/scratch/medial_septum_sct/Data/Derived/Pseudobulk_DEG/DGEList/", currentcell, ".RDS"))
  
  ##Normative
  resultlist_normative <- list()
  design <- model.matrix(~ Genotype, data=dge$samples)
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3)
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_normative[["XXF_vs_XYM"]] <- topTable(fit, n = Inf, adjust.method = "BH", coef = "GenotypeXXF")
  save(resultlist_normative, file = paste0("~/scratch/medial_septum_sct/Data/Derived/Pseudobulk_DEG/normative/", currentcell,".rda"))
  
  ##FCG
  resultlist_fcg <- list()
  dge_samples <- dge$samples[dge$samples$SexChrom %in% c("XY", "XX"), ]
  dge_samples$SexChrom <- factor(dge_samples$SexChrom, levels = c("XY", "XX"))
  dge_counts <- dge$counts[, colnames(dge$counts) %in% rownames(dge_samples)]
  
  design <- model.matrix(~ Gonad + SexChrom + Gonad:SexChrom, data=dge_samples)
  y <- new("EList")
  y$E <- edgeR::cpm(dge_counts, log = TRUE, prior.count = 3)
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_fcg[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_fcg[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "SexChromXX")
  resultlist_fcg[["Ovary:SexChromXX"]] <- topTable(fit, n = Inf, coef = "GonadFemale:SexChromXX")
  
  save(resultlist_fcg, file = paste0("~/scratch/medial_septum_sct/Data/Derived/Pseudobulk_DEG/FCG/", currentcell,".rda"))
  
  ##Aneuploidy
  resultlist_aneuploidy <- list()
  design <- model.matrix(~Gonad + base_SexChrom + Trisomy, data = dge$samples)
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3)
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_aneuploidy[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_aneuploidy[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "base_SexChromXX")
  resultlist_aneuploidy[["Aneuploidy"]] <- topTable(fit, n = Inf, coef = "TrisomyTrisomy")
  
  save(resultlist_aneuploidy, file = paste0("~/scratch/medial_septum_sct/Data/Derived/Pseudobulk_DEG/Aneuploidy/", currentcell,".rda"))
  
  ##Dose model
  resultlist_dose <- list()
  design <- model.matrix(~Gonad + Xdose + Ydose, data = dge$samples) 
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3)
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_dose[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_dose[["Xdose"]] <- topTable(fit, n = Inf, coef = "Xdose")
  resultlist_dose[["Ydose"]] <- topTable(fit, n = Inf, coef = "Ydose")
  
  save(resultlist_dose, file = paste0("~/scratch/medial_septum_sct/Data/Derived/Pseudobulk_DEG/Dose/", currentcell,".rda"))
  
  ##Quadratic model
  resultlist_quad <- list()
  design <- model.matrix(~Gonad + Xdose + poly(Ydose, degree=2), data = dge$samples) 
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3)
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_quad[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_quad[["Xdose"]] <- topTable(fit, n = Inf, coef = "Xdose")
  resultlist_quad[["Ydose"]] <- topTable(fit, n = Inf, coef = "poly(Ydose, degree = 2)1")
  resultlist_quad[["Ydose^2"]] <- topTable(fit, n = Inf, coef = "poly(Ydose, degree = 2)2")
  
  save(resultlist_quad, file = paste0("~/scratch/medial_septum_sct/Data/Derived/Pseudobulk_DEG/Quadratic/", currentcell,".rda"))
  
}

```
## Individual Models
```{r}
##Normative
design <- model.matrix(~ Genotype, data=dge$samples)
y <- new("EList")
y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3)
fit <- lmFit(y, design = design)
#contrasts <- makeContrasts(XXF_vs_XYM = GenotypeXXF - GenotypeXYM, levels = design)
#fit <- contrasts.fit(fit, contrasts)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)

resultlist_normative[["XXF_vs_XYM"]] <- topTable(fit, n = Inf, adjust.method = "BH", coef = "GenotypeXXF")
save(resultlist_normative, file = paste0("Data/Derived/Pseudobulk_DEG/normative/", currentcell,".rda"))
```

```{r}
##FCG
dge_samples <- dge$samples[dge$samples$SexChrom %in% c("XY", "XX"), ]
dge_samples$SexChrom <- factor(dge_samples$SexChrom, levels = c("XY", "XX"))
dge_counts <- dge$counts[, colnames(dge$counts) %in% rownames(dge_samples)]

design <- model.matrix(~ Gonad + SexChrom + Gonad:SexChrom, data=dge_samples)
y <- new("EList")
y$E <- edgeR::cpm(dge_counts, log = TRUE, prior.count = 3)
fit <- lmFit(y, design = design)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)

resultlist_fcg[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
resultlist_fcg[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "SexChromXX")
resultlist_fcg[["Ovary:SexChromXX"]] <- topTable(fit, n = Inf, coef = "GonadFemale:SexChromXX")

save(resultlist_fcg, file = paste0("Data/Derived/Pseudobulk_DEG/FCG/", currentcell,".rda"))
```

```{r}
##Aneuploidy
design <- model.matrix(~Gonad + base_SexChrom + Trisomy, data = dge$samples)
y <- new("EList")
y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3)
fit <- lmFit(y, design = design)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)

resultlist_aneuploidy[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
resultlist_aneuploidy[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "base_SexChromXX")
resultlist_aneuploidy[["Aneuploidy"]] <- topTable(fit, n = Inf, coef = "TrisomyTrisomy")

save(resultlist_aneuploidy, file = paste0("Data/Derived/Pseudobulk_DEG/Aneuploidy/", currentcell,".rda"))
```

```{r}
##Dose model
design <- model.matrix(~Gonad + Xdose + Ydose, data = dge$samples) 
y <- new("EList")
y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3)
fit <- lmFit(y, design = design)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)

resultlist_dose[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
resultlist_dose[["Xdose"]] <- topTable(fit, n = Inf, coef = "Xdose")
resultlist_dose[["Ydose"]] <- topTable(fit, n = Inf, coef = "Ydose")

save(resultlist_dose, file = paste0("Data/Derived/Pseudobulk_DEG/Dose/", currentcell,".rda"))
```

```{r}
##Quadratic model
design <- model.matrix(~Gonad + Xdose + poly(Ydose, degree=2), data = dge$samples) 
y <- new("EList")
y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3)
fit <- lmFit(y, design = design)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)

resultlist_quad[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
resultlist_quad[["Xdose"]] <- topTable(fit, n = Inf, coef = "Xdose")
resultlist_quad[["Ydose"]] <- topTable(fit, n = Inf, coef = "poly(Ydose, degree = 2)1")
resultlist_quad[["Ydose^2"]] <- topTable(fit, n = Inf, coef = "poly(Ydose, degree = 2)2")

save(resultlist_quad, file = paste0("Data/Derived/Pseudobulk_DEG/Quadratic/", currentcell,".rda"))
```

