#install.packages("Seurat")
install.packages("https://cran.r-project.org/src/contrib/Matrix_1.6-3.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.rstudio.com/src/contrib/scattermore_1.2.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/sctransform_0.4.1.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/remaCor_0.0.16.tar.gz", type = "source", repos = NULL)
install.packages("https://cran.r-project.org/src/contrib/tidytree_0.4.6.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/rvcheck/rvcheck_0.1.8.tar.gz", repos = NULL)
install.packages("https://cran.r-project.org/src/contrib/aplot_0.2.2.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.rstudio.com/src/contrib/ggfun_0.1.4.tar.gz", repos = NULL, type = "source")

remotes::install_version("SeuratObject", "4.1.4", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
remotes::install_version("Seurat", "4.4.0", repos = c("https://satijalab.r-universe.dev", getOption("repos")))

install.packages("UpSetR")
install.packages("ComplexUpset")
install.packages("ggplotify")
install.packages("igraph")
install.packages("RANN")
install.packages("WeightedCluster")
install.packages("corpcor")
install.packages("weights")
install.packages("writexl")
install.packages('TMB', type = 'source')
install.packages('Signac')
install.packages("rsvd")
install.packages("tidyverse")
install.packages("EnvStats")
install.packages("ggpubr")
install.packages("mashr")
install.packages("str2str")
install.packages("ggplotify")
install.packages("GGally")
install.packages("ggbreak")
install.packages("enrichR")
install.packages("tidytree")
install.packages("yulab.utils")
install.packages("matrixTests")
install.packages("ggvenn")
install.packages('GOplot')
install.packages("ggnewscale")
install.packages("DGEobj.utils")
install.packages("pdftools")
install.packages("tm")
#install.packages("ggridges")
#install.packages("tigerstats")
#install.packages("glmmSeq")

#BiocManager::install("GOSemSim")
#BiocManager::install("simplifyEnrichment")
BiocManager::install("EnhancedVolcano")
BiocManager::install("biomaRt")
BiocManager::install("Mus.musculus")
BiocManager::install("muscat")
BiocManager::install("AnnotationHub")
BiocManager::install("ensembldb")
BiocManager::install("MAST")
BiocManager::install("scater")
BiocManager::install("limma")
BiocManager::install("treeio")
BiocManager::install("TxDb.Mmusculus.UCSC.mm10.knownGene")
BiocManager::install("ggtree")
BiocManager::install("clusterProfiler")
BiocManager::install("enrichplot")
BiocManager::install("DOSE")
BiocManager::install("GOSemSim")
BiocManager::install("simplifyEnrichment")
BiocManager::install("ANCOMBC")
BiocManager::install("GeneOverlap")
BiocManager::install("DropletUtils")
#BiocManager::install("zellkonverter")
#BiocManager::install("LoomExperiment")

devtools::install_github("lhe17/nebula")
devtools::install_github("jokergoo/ComplexHeatmap")
remotes::install_github("mojaveazure/seurat-disk")
remotes::install_github("satijalab/azimuth", quiet = TRUE)
remotes::install_github("satijalab/seurat-wrappers", quiet = TRUE)
devtools::install_github("DiseaseNeurogenomics/variancePartition")
devtools::install_github("DiseaseNeurogenomics/dreamlet")
remotes::install_github('kevinblighe/EnhancedVolcano')
devtools::install_github("YuLab-SMU/yulab.utils")
devtools::install_github("wjawaid/enrichR")
devtools::install_github("jbisanz/qiime2R")
devtools::install_github("adrientaudiere/MiscMetabar")
devtools::install_github("RRHO2/RRHO2", build_opts = c("--no-resave-data", "--no-manual"))
remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
#remotes::install_github('https://github.com/ekernf01/DoubletFinder', force = T)
remotes::install_github('lzmcboy/DoubletFinder_204_fix')
#devtools::install_github("cellgeni/sceasy")
#devtools::install_github("zhanghao-njmu/SCP")
#devtools::install_github("rpolicastro/scProportionTest")
#devtools::install_github("GfellerLab/SuperCell")
#devtools::install_github("DiseaseNeurogenomics/zenith")


