---
title: "medial septum analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/u/project/xyang123/julianas/medial_septum_sct")
```

```{r}
library(limma)
library(edgeR)
library(data.table)
library(dplyr)
library(fastDummies)
library(plyr)
library(Seurat)
library(clusterProfiler)
library(enrichplot)
library(org.Mm.eg.db)
library(ggplot2)
library(RColorBrewer)
library(grid)
library(gridExtra)
library(corrplot)
library(readxl)
library(biomaRt)

```

```{r}
##Load in files 
seurat <- readRDS("Saves/For_Figures.rds")

gene_list <- rownames(seurat@assays$RNA@counts)
length(gene_list) #32285 genes 
write.table(gene_list, file = "Gene_annotation/genes.txt", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
```

##Biomart and manual annotation
```{r}
ensembl <- useMart("ensembl")
ensembl <- useDataset("mmusculus_gene_ensembl",mart=ensembl)

gene_annotation <- getBM(c("mgi_symbol", "ensembl_gene_id", "chromosome_name", "start_position", "end_position"),
      "mgi_symbol",
      gene_list,
      ensembl)
write.table(gene_annotation, file = "Gene_annotation/gene_annotation_biomart.txt", sep = "\t")

##process genes unannotated by biomart
missing_genes <- gene_list[!gene_list %in% gene_annotation$mgi_symbol]
write.table(missing_genes, file = "Gene_annotation/missing_genes_biomart.txt", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)

##manual gene info 
missing_gene_annotation <- read.table(file = "Gene_annotation/missing_gene_biomart_info.txt", header = TRUE, sep = "\t")
missing_gene_annotation <- missing_gene_annotation %>% dplyr::filter(!grepl("synonym|human|rat", Input.Type))

unannotated_genes <- missing_genes[!missing_genes %in% missing_gene_annotation$Input]
write.table(unannotated_genes, file = "Gene_annotation/missing_genes_biomart.txt", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)

missing_gene_annotation2 <- read.table(file = "Gene_annotation/missing_gene_biomart_info2.txt", header = TRUE, sep = "\t")
missing_gene_annotation2 <- missing_gene_annotation2 %>% dplyr::filter(!grepl("synonym|human|rat", Input.Type))

##create df for unannotated genes 
missing_genes <- rbind(missing_gene_annotation %>% dplyr::filter(MGI.Gene.Marker.ID == "No associated gene"), missing_gene_annotation2 %>% dplyr::filter(MGI.Gene.Marker.ID == "No associated gene"))

##merge 3 gene annotation sets 
missing_gene_annotation <- missing_gene_annotation %>% 
  dplyr::filter(!MGI.Gene.Marker.ID == "No associated gene") %>%
  dplyr::select(Input, Ensembl.ID, Chr, Start, End) %>%
  dplyr::rename(mgi_symbol = Input, ensembl_gene_id = Ensembl.ID, chromosome_name = Chr, start_position = Start, end_position = End)
missing_gene_annotation2 <- missing_gene_annotation2 %>% 
  dplyr::filter(!MGI.Gene.Marker.ID == "No associated gene") %>%
  dplyr::select(Input, Ensembl.ID, Chr, Start, End) %>%
  dplyr::rename(mgi_symbol = Input, ensembl_gene_id = Ensembl.ID, chromosome_name = Chr, start_position = Start, end_position = End)

gene_annotation_final <- rbind(gene_annotation, missing_gene_annotation, missing_gene_annotation2)

##manually annotate version genes 
version_genes <- missing_genes %>% dplyr::filter(grepl("\\.", Input)) 
pseudo_unattached_genes <- missing_genes %>% dplyr::filter(!grepl("\\.", Input))

pseudo_list <- list()

for (i in 1:nrow(version_genes)) {
  Input <- version_genes[i,1]
  Input2 <- gsub("\\..*", "", Input)
  version_genes[i, "Input2"] <- Input2
  
  if (Input2 %in% gene_annotation_final$mgi_symbol == TRUE) {
    matched_annotation <- gene_annotation_final %>% dplyr::filter(mgi_symbol == Input2)
    
    pseudo_list[[i]] <- version_genes[i, ] %>%
      left_join(matched_annotation, by = c("Input2"="mgi_symbol"), multiple = "all") %>%
      dplyr::select(Input, Input.Type, Input2, ensembl_gene_id, chromosome_name, start_position, end_position) %>%
      dplyr::mutate(Input.Type = "Manual")
  } else {
    
    pseudo_list[[i]] <- version_genes[i, ] %>%
      dplyr::select(Input, Input.Type, Input2, Ensembl.ID, Chr, Start, End) %>%
      dplyr::rename(ensembl_gene_id = Ensembl.ID,
                    chromosome_name = Chr,
                    start_position = Start,
                    end_position = End)
    
  }
}
version_genes_results <- dplyr::bind_rows(pseudo_list)

##manually annotate unannotated sequences? 
version_genes_results %>% dplyr::filter(is.na(start_position))

```

```{r}
##manually annotate pseudogene/unattached genes 
pseudo_unattached_genes <- pseudo_unattached_genes %>%
  mutate(Feature.Type = ifelse(grepl("ps|OR5BS1P", Input), "Pseudogene", NA))
pseudo_unattached_genes[pseudo_unattached_genes$Input == "Ancv1r", ] <- pseudo_unattached_genes[pseudo_unattached_genes$Input == "Ancv1r", ] %>% 
  mutate(MGI.Gene.Marker.ID = "MGI:6324721",
         Symbol = "Gm50457", 
         Chr = 18,
         Start = 52958344,
         End = 52961362,
         Ensembl.ID = "ENSMUSG00000118407"
         )
pseudo_unattached_genes[pseudo_unattached_genes$Input == "Vmn1r186", ] <- pseudo_unattached_genes[pseudo_unattached_genes$Input == "Vmn1r186", ] %>% 
  mutate(MGI.Gene.Marker.ID = NA,
         Feature.Type = "Unlocalized scaffold",
         Symbol = "Vmn1r186", 
         Chr = 7,
         Start = NA,
         End = NA,
         Ensembl.ID = "ENSMUSG00000096776"
         )
pseudo_unattached_genes[pseudo_unattached_genes$Input == "Gm10931", ] <- pseudo_unattached_genes[pseudo_unattached_genes$Input == "Gm10931", ] %>% 
  mutate(MGI.Gene.Marker.ID = NA,
         Feature.Type = "No associated gene",
         Symbol = NA, 
         Chr = NA,
         Start = NA,
         End = NA,
         Ensembl.ID = NA
         )
pseudo_unattached_genes[pseudo_unattached_genes$Input == "Cccd201", ] <- pseudo_unattached_genes[pseudo_unattached_genes$Input == "Cccd201", ] %>% 
  mutate(MGI.Gene.Marker.ID = "MGI:3650614",
         Feature.Type = "ncRNA",
         Symbol = "Ccdc201", 
         Chr = 11,
         Start = 7133157,
         End = 7138569,
         Ensembl.ID = "ENSMUSG00000087512"
         )


version_genes_results$Feature.Type <- "Gene version"
pseudo_unattached_genes$Input2 <- NA
pseudo_unattached_genes <- pseudo_unattached_genes %>%
  dplyr::select(Input, Input.Type, Input2, Ensembl.ID, Chr, Start, End, Feature.Type) %>% 
  dplyr::rename(ensembl_gene_id = Ensembl.ID,
                    chromosome_name = Chr,
                    start_position = Start,
                    end_position = End)

manual_gene_annotation <- rbind(version_genes_results, pseudo_unattached_genes) %>% 
  dplyr::select(Input, ensembl_gene_id, chromosome_name, start_position, end_position, Feature.Type) %>%
  dplyr::rename(mgi_symbol = Input)

gene_annotation_final$Feature.Type <- "RNA"
gene_annotation_final <- gene_annotation_final %>% mutate(Feature.Type = ifelse(is.na(gene_annotation_final$start_position), "Unlocalized scaffold", gene_annotation_final$Feature.Type))

gene_annotation_final2 <- rbind(gene_annotation_final, manual_gene_annotation)
empty_as_na <- function(x){
    if("factor" %in% class(x)) x <- as.character(x) ## since ifelse wont work with factors
    ifelse(as.character(x)!="", x, NA)
}

gene_annotation_final2 <- gene_annotation_final2 %>% mutate_each(funs(empty_as_na))

write.table(gene_annotation_final2, file = "Gene_annotation/gene_annotation_final2.txt", sep = "\t", col.names=TRUE, row.names = FALSE)
```

```{r}

version_genes$Input2 <- gsub("\\..*", "", missing_genes1$Input)

write.table(missing_genes1$Input2, file = "Gene_annotation/missing_genes_biomart2.txt", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)

same_genes1 <- missing_genes1[missing_genes1$Input2 %in% missing_gene_annotation$Input, ] #2 genes
same_genes1 <- left_join(same_genes1[c(1,11)], missing_gene_annotation, by=c("Input2"="Input"))

same_genes2 <- missing_genes1[missing_genes1$Input2 %in% gene_annotation$mgi_symbol, ] #23 genes
same_genes2 <- left_join(same_genes2[c(1,11)], gene_annotation, by=c("Input2"="mgi_symbol")) %>%
  dplyr::rename(gene_id = ensembl_gene_id)

#remove missing annotation for genes in same_genes1 and same_genes2 and add back to updated gene annotation df 
missing_gene_annotation2 <- missing_gene_annotation %>% dplyr::filter(!Input %in% c(same_genes1$Input, same_genes2$Input))
missing_gene_annotation2$Input2 <- NA
missing_gene_annotation2 <- missing_gene_annotation2 %>% relocate(Input, Input2)
missing_gene_annotation2 <- rbind(missing_gene_annotation2, same_genes1)
missing_gene_annotation2 <- missing_gene_annotation2 %>% 
  dplyr::select(Input, Input2, MGI.Gene.Marker.ID, Chr, Start, End) %>%
  dplyr::rename(gene_id = MGI.Gene.Marker.ID, 
                chromosome_name = Chr, 
                start_position = Start,
                end_position = End)
missing_gene_annotation2 <- rbind(missing_gene_annotation2, same_genes2)

#find genes that still lack annotation 
no_annotation_genes <- missing_genes1[!missing_genes1$Input2 %in% c(missing_gene_annotation$Input, gene_annotation$mgi_symbol), ] #95 remaining genes 
no_annotation_genes <- no_annotation_genes %>% 
  relocate(Input, Input2) %>%
  dplyr::select(Input, Input2, MGI.Gene.Marker.ID, Chr, Start, End) %>%
  dplyr::rename(gene_id = MGI.Gene.Marker.ID, 
                chromosome_name = Chr, 
                start_position = Start,
                end_position = End)

gene_annotation$Input2 <- NA
gene_annotation <- gene_annotation %>% 
  relocate(mgi_symbol, Input2) %>%
  dplyr::rename(Input = mgi_symbol,
                gene_id = ensembl_gene_id)
gene_annotation_final <- rbind(gene_annotation, missing_gene_annotation2)

write.table(gene_annotation_final, file = "Gene_annotation/gene_annotation_final2.txt", sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
```


##Manual annotation 
```{r}
gene_info <- read.table("Gene_annotation/gene_info_filtered.txt", sep = "\t", check.names= FALSE, header = TRUE, fill = TRUE, quote="")
gene_info <- gene_info[-27201, ] ##duplicated marker

missing_genes <- gene_info %>% dplyr::filter(`MGI Gene/Marker ID` == "No associated gene") %>% dplyr::select(Input) %>% unlist()
write.table(missing_genes, file = "Gene_annotation/missing_genes.txt", row.names = FALSE, col.names = FALSE, quote = FALSE)

missing_gene_info <- read.table("Gene_annotation/missing_gene_info.txt", sep = "\t", check.names = FALSE, header = TRUE, fill = TRUE, quote = "") %>%
  dplyr::filter(`Input Type` %in% c("", "old symbol"))

genes_to_reannotate <- missing_gene_info %>% dplyr::filter(`MGI Gene/Marker ID` == "No associated gene")

gene_info <- gene_info %>% dplyr::filter(!`MGI Gene/Marker ID` == "No associated gene")
missing_gene_info <- missing_gene_info  %>% dplyr::filter(!`MGI Gene/Marker ID` == "No associated gene")
gene_info <- rbind(gene_info, missing_gene_info)

for (i in 1:nrow(genes_to_reannotate)) {
  
  original_gene <- genes_to_reannotate[i, "Input"]
  if(grepl("\\.", original_gene) == FALSE ) {next}
  matching_gene <- gsub("\\..*", "", original_gene)
  
  matching_gene_info <- gene_info %>% dplyr::filter(Input == matching_gene)
  if(nrow(matching_gene_info) == 0) {next}
  
  genes_to_reannotate[i, 2:ncol(genes_to_reannotate)] <- matching_gene_info[2:ncol(matching_gene_info)]
  genes_to_reannotate[i, ]
}

for (i in 1:nrow(genes_to_reannotate)) {
  
  original_gene <- genes_to_reannotate[i, "Input"]
  if(grepl("-", original_gene) == FALSE ) {next}
  matching_gene <- gsub("-.*", "", original_gene)
  
  matching_gene_info <- gene_info %>% dplyr::filter(Input == matching_gene)
  if(nrow(matching_gene_info) == 0) {next}
  
  genes_to_reannotate[i, 2:ncol(genes_to_reannotate)] <- matching_gene_info[2:ncol(matching_gene_info)]
  genes_to_reannotate[i, ]
}

genes_to_reannotate %>% dplyr::filter(`MGI Gene/Marker ID` == "No associated gene") ##finish annotation for last 144? 

gene_info <- rbind(gene_info, genes_to_reannotate)
```

```{r}
xescape_brain <- read_xlsx("Gene_annotation/xescape_brain.xlsx")
colnames(xescape_brain) <- xescape_brain[1, ]
xescape_brain <- xescape_brain[-1, ]

xescape_brain
```

```{r}
gene_info$Gene_class <- ifelse(gene_info$Chr %in% c("X", "Y"), "Sex-linked", "Autosome")
gene_info$PAR <- ifelse(gene_info$Input %in% c("Mid1", "Sts", "Nlgn4", "Asmt"), "PAR", "Non-PAR")
gene_info$Xescape <- ifelse(gene_info$Input %in% xescape_brain$Gene, "Escapee", "Non-escapee")

write.table(gene_info, file = "Gene_annotation/gene_annotation_final.txt", sep = "\t")
```

