---
title: "DEG2"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/u/project/xyang123/jshin/medial_septum_sct")

library(limma)
library(edgeR)
library(data.table)
library(dplyr)
library(plyr)
library(Seurat)
#library(clusterProfiler)
#library(enrichplot)
library(org.Mm.eg.db)
library(ggplot2)
library(RColorBrewer)
library(grid)
library(gridExtra)
```

```{r}
##Load in files 
#load("Data/Derived/metadata.Rda")
seurat <- readRDS("/u/home/j/jshin/scratch/medial_septum_sct/Saves/MS_cellbender_complete_saves/seurat_harmony_sampleid_filtered_annotated.Rds")
```

```{r, eval = FALSE}
##Edit metadata 
seurat$Xdose <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(2, 2, 1 ,1)) %>% factor(levels = c(1, 2))
seurat$Xdose_cont <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(2, 2, 1 ,1)) %>% as.character() %>% as.numeric()
seurat$Ydose <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 1 ,2)) %>% factor(levels = c(0, 1, 2))
seurat$Ydose_cont <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 1 ,2)) %>% as.character() %>% as.numeric()
seurat$base_SexChrom <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c("XX", "XY", "XY", "XY")) %>% factor(levels = c("XY", "XX"))
seurat$trisomyX <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XY", "XX", "XXY", "XYY"),
                                       to = c(0, 0, 1, 0)) %>% as.numeric()
seurat$trisomyY <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XY", "XX", "XXY", "XYY"),
                                       to = c(0, 0, 0, 1)) %>% as.numeric()


##previous analysis
seurat$GenotypeaddX <- plyr::mapvalues(seurat$Genotype,
                                       from = c("XYM", "XYF", "XXYM", "XXYF"),
                                       to = c("XYM", "XYF", "XYM", "XYF")) %>% factor(levels = c("XYM", "XYF"))
seurat$addX <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XY", "XXY"),
                                       to = c(0, 1)) %>% as.numeric()
seurat$GenotypeaddY <- plyr::mapvalues(seurat$Genotype,
                                       from = c("XXM", "XXF", "XXYM", "XXYF", "XYM", "XYF", "XYYM", "XYYF"),
                                       to = c("XXM", "XXF", "XXM", "XXF", "XYM", "XYF", "XYM", "XYF")) %>% factor(levels = c("XYM", "XYF", "XXM", "XXF"))
seurat$addY <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XX", "XXY", "XY", "XYY"),
                                       to = c(0, 1, 0, 1)) %>% as.numeric()
seurat$addY1 <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XX", "XXY", "XY", "XYY"),
                                       to = c(0, 1, 0, 0)) %>% as.numeric()
seurat$addY2 <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XX", "XXY", "XY", "XYY"),
                                       to = c(0, 0, 0, 1)) %>% as.numeric()


seurat$Gonad <- factor(seurat$Gonad, levels = c("Male", "Female"))
seurat$SexChrom <- factor(seurat$SexChrom, levels = c("XY", "XX", "XYY", "XXY"))
seurat$Genotype <- factor(seurat$Genotype, levels = c("XYM", "XYF", "XXM", "XXF", "XYYM", "XYYF", "XXYM", "XXYF"))
seurat$Trisomy <- factor(seurat$Trisomy, levels = c("Non-Trisomy", "Trisomy"))
```

###################################

LINEAR MODELING WITH LIMMA 

```{r}
#test class
allcells <- unique(seurat@meta.data$cell.type2)
allcells <- allcells[!allcells %in% c("Other", "Unknown")]

#test subclass
allcells <- unique(seurat@meta.data$subclass_simplify)
allcells <- allcells[!allcells %in% c("Other", "Unknown", "Astroependymal", "Choroid", "Pericyte", "VLMC")]

#test new cell types
allcells <- unique(seurat@meta.data$celltype)
#newcells <- c("Neuron", "Astrocyte", "Oligo.PC", "Microglia", "Progenitor", "Myelinating.Oligo", "Endothelial", "Ependymal")
```

```{r}
##normative analysis (XYM vs XXM) 
for(i in 1:length(allcells)){
  
  resultlist_normative <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, celltype == currentcell)
  gc()
  
  currentsubset <- currentsubset_original
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~0 + nCount_RNA + nFeature_RNA + Genotype, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  contrasts <- makeContrasts(XXF_vs_XYM = GenotypeXXF - GenotypeXYM,levels = design)
  
  fit <- contrasts.fit(fit, contrasts)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_normative[["XXF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "XXF_vs_XYM")

  save(resultlist_normative, file = paste0("Results/complete_analysis/DEG/normative/", currentcell,".rda"))
}
```

```{r}
##sexchrom and gonad analysis (FCG)

for(i in 1:length(allcells)) {
  
  resultlist_fcg <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, celltype == currentcell & Genotype %in% c("XYM","XXF","XXM" ,"XYF"))
  gc()
  
  currentsubset <- subset(currentsubset_original)
  currentsubset$Genotype <- factor(currentsubset$Genotype, levels = c("XYM","XXF","XXM" ,"XYF"))
  currentsubset$SexChrom <- factor(currentsubset$SexChrom, levels = c("XY", "XX"))
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + Gonad + SexChrom + Gonad:SexChrom, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_fcg[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_fcg[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "SexChromXX")
  resultlist_fcg[["Ovary:SexChromXX"]] <- topTable(fit, n = Inf, coef = "GonadFemale:SexChromXX")
  
  save(resultlist_fcg, file = paste0("Results/DEG_v3/celltype2/FCG/", currentcell,".rda"))
}
```

```{r}
##additionalX analysis (previous style) - continuous

for(i in 1:length(allcells)) {
  
  resultlist_additionalX_cont <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, celltype == currentcell & SexChrom %in% c("XY", "XXY"))
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  currentsubset$addX <- currentsubset$addX %>% as.character() %>% as.numeric()
  datatotest <- currentsubset@meta.data

  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + GenotypeaddX + addX, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_additionalX_cont[["XYF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddXXYF")
  resultlist_additionalX_cont[["addX"]] <- topTable(fit, n = Inf, coef = "addX")
  #resultlist_additionalX_cont[["GenotypeaddXXYF:addX"]] <- topTable(fit, n = Inf, coef = "GenotypeaddXXYF:addX")
  
  save(resultlist_additionalX_cont, file = paste0("Results/DEG_v3/celltype2/addX/", currentcell,".rda"))
}
```

```{r}
##additionalY1 analysis (previous style)

for(i in 1:length(allcells)) {
  
  resultlist_additionalY1 <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, celltype == currentcell & SexChrom %in% c("XX", "XXY"))
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + GenotypeaddY + addY1, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_additionalY1[["XYF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXYF")
  resultlist_additionalY1[["XXM_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXM")
  resultlist_additionalY1[["XXF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXF")
  resultlist_additionalY1[["addY1"]] <- topTable(fit, n = Inf, coef = "addY1")
  #resultlist_additionalY[["addY2"]] <- topTable(fit, n = Inf, coef = "addY2")
  # resultlist_additionalY[["GenotypeaddYXYF:addY1"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXYF:addY1")
  # resultlist_additionalY[["GenotypeaddYXXM:addY1"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXM:addY1")
  # resultlist_additionalY[["GenotypeaddYXXF:addY1"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXF:addY1")
  # resultlist_additionalY[["GenotypeaddYXYF:addY2"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXYF:addY2")
  # resultlist_additionalY[["GenotypeaddYXXM:addY2"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXM:addY2")
  # resultlist_additionalY[["GenotypeaddYXXF:addY2"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXF:addY2")
  
  save(resultlist_additionalY1, file = paste0("Results/DEG_v3/celltype2/addY1/", currentcell,".rda"))
}
```

```{r}
##additionalY2 analysis (previous style)

for(i in 1:length(allcells)) {
  
  resultlist_additionalY2 <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, celltype == currentcell & SexChrom %in% c("XY", "XYY"))
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + GenotypeaddY + addY2, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_additionalY2[["XYF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXYF")
  resultlist_additionalY2[["XXM_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXM")
  resultlist_additionalY2[["XXF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXF")
  resultlist_additionalY2[["addY2"]] <- topTable(fit, n = Inf, coef = "addY2")
  # resultlist_additionalY[["GenotypeaddYXYF:addY1"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXYF:addY1")
  # resultlist_additionalY[["GenotypeaddYXXM:addY1"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXM:addY1")
  # resultlist_additionalY[["GenotypeaddYXXF:addY1"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXF:addY1")
  # resultlist_additionalY[["GenotypeaddYXYF:addY2"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXYF:addY2")
  # resultlist_additionalY[["GenotypeaddYXXM:addY2"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXM:addY2")
  # resultlist_additionalY[["GenotypeaddYXXF:addY2"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXF:addY2")
  
  save(resultlist_additionalY2, file = paste0("Results/DEG_v3/celltype2/addY2/", currentcell,".rda"))
}
```

##Extra models 

```{r}
##additionalY analysis (previous style) - continuous

for(i in 1:length(allcells)) {
  
  resultlist_additionalY_cont <- list()
  
  currentcell <- as.character(allcells[i])
  newcell <- as.character(newcells[i]) ##rename
  currentsubset_original <- subset(seurat, cell.type == currentcell & SexChrom %in% c("XY", "XX", "XXY", "XYY"))
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  currentsubset$addY <- currentsubset$addY %>% as.character() %>% as.numeric()
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + GenotypeaddY + addY, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_additionalY_cont[["XYF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXYF")
  resultlist_additionalY_cont[["XXM_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXM")
  resultlist_additionalY_cont[["XXF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXF")
  resultlist_additionalY_cont[["addY"]] <- topTable(fit, n = Inf, coef = "addY")
  # resultlist_additionalY_cont[["GenotypeaddYXYF:addY"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXYF:addY")
  # resultlist_additionalY_cont[["GenotypeaddYXXM:addY"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXM:addY")
  # resultlist_additionalY_cont[["GenotypeaddYXXF:addY"]] <- topTable(fit, n = Inf, coef = "GenotypeaddYXXF:addY")
  
  save(resultlist_additionalY_cont, file = paste0("Results/DEG_v2/addY/", newcell,".rda"))
}
```

```{r}
##complete model 

for(i in 1:length(allcells)) {
  
  resultlist_complete <- list()
  
  currentcell <- as.character(allcells[i])
  newcell <- as.character(newcells[i]) ##rename
  currentsubset_original <- subset(seurat, cell.type == currentcell)
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  currentsubset$addY <- currentsubset$addY %>% as.character() %>% as.numeric()
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + Gonad + base_SexChrom + trisomyX + trisomyY, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_complete[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_complete[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "base_SexChromXX")
  resultlist_complete[["addX"]] <- topTable(fit, n = Inf, coef = "trisomyX")
  resultlist_complete[["addY"]] <- topTable(fit, n = Inf, coef = "trisomyY")
  
  save(resultlist_complete, file = paste0("Results/DEG_v2/complete/", newcell,".rda"))
}
```

```{r}
##Xdose Ydose compensatory analysis

for(i in 1:length(allcells)) {
  
  resultlist_fcg_dose <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, cell.type == currentcell & Genotype %in% c("XYM","XXF","XXM" ,"XYF"))
  gc()
  
  currentsubset <- subset(currentsubset_original)
  currentsubset$Genotype <- factor(currentsubset$Genotype, levels = c("XYM","XXF","XXM" ,"XYF"))
  currentsubset$SexChrom <- factor(currentsubset$SexChrom, levels = c("XY", "XX"))
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + Xdose_cont + Ydose_cont, data = datatotest) 

  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_fcg_dose[["Xdose"]] <- topTable(fit, n = Inf, coef = "Xdose_cont")

  save(resultlist_fcg_dose, file = paste0("Data/Derived/DEG/FCG_dose/", currentcell,".rda"))
}
```

```{r}
##Armin: XXY and XYY vs XY

##males only (2 pairwise comparisons)
for(i in 1:length(allcells)){
  
  resultlist_XY_male <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, cell.type == currentcell & Gonad == "Male")
  gc()
  
  currentsubset <- currentsubset_original
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~0 + nCount_RNA + nFeature_RNA + SexChrom, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  contrasts <- makeContrasts(XXY_vs_XY = SexChromXXY - SexChromXY,
                             XYY_vs_XY = SexChromXYY - SexChromXY, 
                           levels = design)
  
  fit <- contrasts.fit(fit, contrasts)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_XY_male[["XXY_vs_XY"]] <- topTable(fit, n = Inf, coef = "XXY_vs_XY")
  resultlist_XY_male[["XYY_vs_XY"]] <- topTable(fit, n = Inf, coef = "XYY_vs_XY")

  save(resultlist_XY, file = paste0("Data/Derived/DEG/XY_male/", currentcell,".rda"))
}

##females only (2 pairwise comparisons)
for(i in 1:length(allcells)){
  
  resultlist_XY_female <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, cell.type == currentcell & Gonad == "Female")
  gc()
  
  currentsubset <- currentsubset_original
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~0 + nCount_RNA + nFeature_RNA + SexChrom, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  contrasts <- makeContrasts(XXY_vs_XY = SexChromXXY - SexChromXY,
                             XYY_vs_XY = SexChromXYY - SexChromXY, 
                           levels = design)
  
  fit <- contrasts.fit(fit, contrasts)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_XY_female[["XXY_vs_XY"]] <- topTable(fit, n = Inf, coef = "XXY_vs_XY")
  resultlist_XY_female[["XYY_vs_XY"]] <- topTable(fit, n = Inf, coef = "XYY_vs_XY")

  save(resultlist_XY_female, file = paste0("Data/Derived/DEG/XY_female/", currentcell,".rda"))
}

##gonad collapsed - take only genes without significant gonadal interaction effect 

for(i in 1:length(allcells)){
  
  resultlist_XY_comb <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, cell.type == currentcell)
  gc()
  
  currentsubset <- currentsubset_original
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~0 + nCount_RNA + nFeature_RNA + SexChrom + SexChrom:Gonad, data = datatotest) 
  colnames(design) <- gsub(":", ".", colnames(design))
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  contrasts <- makeContrasts(XXY_vs_XY = SexChromXXY - SexChromXY,
                             XYY_vs_XY = SexChromXYY - SexChromXY, 
                             `SexChromXY.GonadFemale` = `SexChromXY.GonadFemale`, 
                             `SexChromXX.GonadFemale` = `SexChromXX.GonadFemale`, 
                             `SexChromXYY.GonadFemale` = `SexChromXYY.GonadFemale`,
                             `SexChromXXY.GonadFemale` = `SexChromXXY.GonadFemale`,
                           levels = design)
  
  fit <- contrasts.fit(fit, contrasts)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_XY_comb[["XXY_vs_XY"]] <- topTable(fit, n = Inf, coef = "XXY_vs_XY")
  resultlist_XY_comb[["XYY_vs_XY"]] <- topTable(fit, n = Inf, coef = "XYY_vs_XY")
  resultlist_XY_comb[["SexChromXY:GonadFemale"]] <- topTable(fit, n = Inf, coef = "SexChromXY.GonadFemale")
  resultlist_XY_comb[["SexChromXX:GonadFemale"]] <- topTable(fit, n = Inf, coef = "SexChromXX.GonadFemale")
  resultlist_XY_comb[["SexChromXYY:GonadFemale"]] <- topTable(fit, n = Inf, coef = "SexChromXYY.GonadFemale")
  resultlist_XY_comb[["SexChromXXY:GonadFemale"]] <- topTable(fit, n = Inf, coef = "SexChromXXY.GonadFemale")
  
  save(resultlist_XY_comb, file = paste0("Data/Derived/DEG/XY_comb/", currentcell,".rda"))
}

```

```{r}
##full model (X and Y dose + gonad)

for(i in 1:length(allcells)) {
  
  resultlist_full <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, cell.type == currentcell)
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + Gonad + Xdose + Ydose + Gonad:Xdose + Gonad:Ydose + Xdose:Ydose, data = datatotest) 
  colnames(design) <- gsub(":", ".", colnames(design))

  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  contrasts <- makeContrasts(GonadFemale = GonadFemale, 
                             Xdose2 = Xdose2,
                             Ydose1 = Ydose1,
                             Ydose2 = Ydose2,
                             `Ydose2-Ydose1` = Ydose2 - Ydose1,
                             `GonadFemale.Xdose2` = `GonadFemale.Xdose2`,
                             `GonadFemale.Ydose1` =`GonadFemale.Ydose1`,
                             `GonadFemale.Ydose2` =`GonadFemale.Ydose2`,
                           levels = design)
  fit <- contrasts.fit(fit, contrasts)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_full[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_full[["Xdose2_vs_Xdose1"]] <- topTable(fit, n = Inf, coef = "Xdose2")
  resultlist_full[["Ydose1_vs_Ydose0"]] <- topTable(fit, n = Inf, coef = "Ydose1")
  resultlist_full[["Ydose2_vs_Ydose0"]] <- topTable(fit, n = Inf, coef = "Ydose2")
  resultlist_full[["Ydose2_vs_Ydose1"]] <- topTable(fit, n = Inf, coef = "Ydose2-Ydose1")
  resultlist_full[["Ovary:Xdose2"]] <- topTable(fit, n = Inf, coef = "GonadFemale.Xdose2")
  resultlist_full[["Ovary:Ydose1"]] <- topTable(fit, n = Inf, coef = "GonadFemale.Ydose1")
  resultlist_full[["Ovary:Ydose2"]] <- topTable(fit, n = Inf, coef = "GonadFemale.Ydose2")

  save(resultlist_full, file = paste0("Data/Derived/DEG/full/", currentcell,".rda"))
}
```

```{r}
##full model (X and Y dose + gonad) - continuous variables

for(i in 1:length(allcells)) {
  
  resultlist_full_cont <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, cell.type == currentcell)
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + Gonad + Xdose_cont + Ydose_cont + Gonad:Xdose_cont + Gonad:Ydose_cont + Xdose_cont:Ydose_cont, data = datatotest) 
  colnames(design) <- gsub(":", ".", colnames(design))

  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_full_cont[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_full_cont[["Xdose"]] <- topTable(fit, n = Inf, coef = "Xdose_cont")
  resultlist_full_cont[["Ydose"]] <- topTable(fit, n = Inf, coef = "Ydose_cont")
  resultlist_full_cont[["Ovary:Xdose"]] <- topTable(fit, n = Inf, coef = "GonadFemale.Xdose_cont")
  resultlist_full_cont[["Ovary:Ydose"]] <- topTable(fit, n = Inf, coef = "GonadFemale.Ydose_cont")
  resultlist_full_cont[["Xdose:Ydose"]] <- topTable(fit, n = Inf, coef = "Xdose_cont.Ydose_cont")

  save(resultlist_full_cont, file = paste0("Data/Derived/DEG/full_cont/", currentcell,".rda"))
}
```

```{r}
##quadratic full model

for(i in 1:length(allcells)) {
  
  resultlist_full_quad <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, cell.type == currentcell)
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + Gonad + Xdose_cont + poly(Ydose_cont, degree=2), data=datatotest)

  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_full_quad[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_full_quad[["Xdose"]] <- topTable(fit, n = Inf, coef = "Xdose_cont")
  resultlist_full_quad[["Ydose"]] <- limma::topTable(fit, n = Inf, coef = 6:7)
  #resultlist_full_quad[["Ydose^2"]] <- topTable(fit, n = Inf, coef = "poly(Ydose_cont, degree = 2)2")

  save(resultlist_full_quad, file = paste0("Data/Derived/DEG/full_quad/", currentcell,".rda"))
}
```

```{r}
##additionalX and additionalY combined analysis 

for(i in 1:length(allcells)) {
  
  resultlist_add <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, cell.type == currentcell)
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + Gonad + base_SexChrom + Trisomy + Gonad:base_SexChrom + Gonad:Trisomy + base_SexChrom:Trisomy, data = datatotest) 
  colnames(design) <- gsub(":", ".", colnames(design))

  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_add[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  resultlist_add[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "base_SexChromXX")
  resultlist_add[["Aneuploidy"]] <- topTable(fit, n = Inf, coef = "TrisomyNon-Trisomy")
  resultlist_add[["Ovary:SexChromXX"]] <- topTable(fit, n = Inf, coef = "GonadFemale.base_SexChromXX")
  resultlist_add[["Ovary:Aneuploidy"]] <- topTable(fit, n = Inf, coef = "GonadFemale.TrisomyNon-Trisomy")
  resultlist_add[["SexChromXX:Aneuploidy"]] <- topTable(fit, n = Inf, coef = "base_SexChromXX.TrisomyNon-Trisomy")

  save(resultlist_add, file = paste0("Data/Derived/DEG/full_add/", currentcell,".rda"))
}
```

```{r}
##additionalX analysis (previous style)

for(i in 1:length(allcells)) {
  
  resultlist_additionalX <- list()
  
  currentcell <- as.character(allcells[i])
  currentsubset_original <- subset(seurat, cell.type == currentcell & SexChrom %in% c("XY", "XXY"))
  gc()
  
  currentsubset <- subset(currentsubset_original)
  test <- currentsubset@assays$RNA@counts
  normalized <- currentsubset@assays$RNA@data
  identical(rownames(test),rownames(normalized))
  datatotest <- currentsubset@meta.data
  
  top2 <- which(Matrix::rowMeans(test >= 1) >= 0.15) #9000 gene > 0.1, 6000 gene > 0.2
  test <- normalized[top2,]
  
  design <- model.matrix(~nCount_RNA + nFeature_RNA + GenotypeaddX + addX + GenotypeaddX:addX, data = datatotest) 
  
  y <- new("EList")
  y$E <- test 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  resultlist_additionalX[["XYF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "GenotypeaddXXYF")
  resultlist_additionalX[["addX1"]] <- topTable(fit, n = Inf, coef = "addX1")
  resultlist_additionalX[["GenotypeaddXXYF:addX1"]] <- topTable(fit, n = Inf, coef = "GenotypeaddXXYF:addX1")
  
  save(resultlist_additionalX, file = paste0("Data/Derived/DEG/addX/", currentcell,".rda"))
}
```