---
title: "Supercell DEG"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/scratch/old-scratch-julianas/medial_septum_sct")

library(limma)
library(edgeR)
library(data.table)
library(dplyr)
library(plyr)
library(Seurat)
library(enrichplot)
library(org.Mm.eg.db)
library(ggplot2)
library(RColorBrewer)
library(grid)
library(gridExtra)
library(stringr)
```

```{r}
##FUNCTIONS

run_venn <- function(x, model, path) {
  pdf(paste0(path, model, "_global.pdf"), onefile = TRUE, width = 20, height = 10)
  par(mfrow = c(2,4))
  for(i in 1:length(x[["global"]])) {
    currentdt <- x[["global"]][[i]]
    currentcell <- x[["global"]][i] %>% names()
    
    vennDiagram(currentdt[,-1]) + title(currentcell, cex.main = 2)
  }
  dev.off()
  
  pdf(paste0(path, model, "_separate.pdf"), onefile = TRUE, width = 20, height = 10)
  par(mfrow = c(2,4))
  for(i in 1:length(x[["separate"]])) {
    currentdt <- x[["separate"]][[i]]
    currentcell <- x[["separate"]][i] %>% names()
    
    vennDiagram(currentdt[,-1]) + title(currentcell, cex.main = 2)
  }
  dev.off()
  
  print("Plots Saved!")
}

get_summary <- function(x) {
  
  global_summary_list <- lapply(x[["global"]], function(x) {summary(x)})
  separate_summary_list <- lapply(x[["separate"]], function(x) {summary(x)})
  
  return(list(separate_summary_list, global_summary_list))
}

```

##Working with multiple cell types - global fit 

```{r}
allcells <- c("Astrocyte","Endothelial","Ependymal","Intermediate_Progenitor_Cell","Microglia","Myelinating_Oligodendrocyte","Neuron","Oligodendrocyte_Progenitor_Cell")
allcells <- gsub(" ", "_", allcells)
allcells <- allcells[-4]
```


```{r}
##Normative
dt_list <- list()
fit_list <- list()
for (i in 1:length(allcells)){
  
  sc_count <- "50"
  currentcell <- allcells[i]
  ct <- paste0(sc_count, "sc_", allcells[i])
  
  seurat <- readRDS(paste0("Saves/Celltype_supercells/", ct, ".RDS")) %>% DietSeurat(counts = TRUE)
  samples_to_remove <- c("XY-TriSeptum-12", "XY-TriSeptum-24", "XY-TriSeptum-2")
  seurat <- subset(seurat, sampleName %in% samples_to_remove, invert = TRUE)
  
  ##Edit metadata 
  seurat$Genotype <- factor(seurat$Genotype, levels = c("XYM", "XYF", "XXM", "XXF", "XYYM", "XYYF", "XXYM", "XXYF"))
  
  ##Normative Difference
  dge0 <- DGEList(seurat@assays$RNA@counts, group = seurat$sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  # keep.exprs <- filterByExpr(dge)
  # dge <- dge[keep.exprs,, keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
    
  design <- model.matrix(~0 + Genotype, data = seurat@meta.data)
    
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  # contrasts <- makeContrasts(XXF_vs_XYM = GenotypeXXF - GenotypeXYM,
  #                            levels = design)
  # fit <- contrasts.fit(fit, contrasts)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  dt1 <- decideTests(fit, method = "separate")
  dt2 <- decideTests(fit, method = "global")
  
  dt_list[["separate"]][[currentcell]] <- dt1
  dt_list[["global"]][[currentcell]] <- dt2
  fit_list[[currentcell]] <- fit 
  
  write.fit(fit, method = "global", adjust = "BH", sep = "\t", quote = FALSE, file = paste0(data.dir, "/Data/Derived/Supercell_DEG/global_fit/fit_results/Normative/", ct, ".txt"))
    
  #resultlist_normative[["XXF_vs_XYM"]][[currentcell]] <- topTable(fit, n = Inf, coef = "XXF_vs_XYM")
}

#run_venn(dt_list, "Normative")
summary <- get_summary(dt_list)
summary[[1]]

##process written fit file 
for(i in 1:length(allcells)) {
  
  resultlist_normative <- list()
  
  currentcell <- allcells[i]
  sc_count <- "50"
  ct <- paste0(sc_count, "sc_", currentcell)
  
  DEresults <- read.table(paste0(data.dir, "/Data/Derived/Supercell_DEG/global_fit/fit_results/Normative/", ct, ".txt"), sep = "\t", header = TRUE, row.names = 1)
  head(DEresults)
  
  resultlist_normative[["XXF_vs_XYM"]] <- DEresults %>% dplyr::select(Coef.GenotypeXXF, t.GenotypeXXF, P.value.GenotypeXXF, P.value.adj.GenotypeXXF, F, F.p.value)
  
  resultlist_normative <- lapply(resultlist_normative, setNames, c("logFC", "T", "P.Val", "adj.P.Val", "F", "F.P.Val"))
  
  save(resultlist_normative, file = paste0(data.dir, "/Data/Derived/Supercell_DEG/global_fit/Normative/", ct,".rda"))
}
```

```{r}
##sexchrom and gonad analysis (FCG)
dt_list <- list()
fit_list <- list()
for (i in 1:length(allcells)) {
  
  sc_count <- "50"
  currentcell <- allcells[i]
  ct <- paste0(sc_count, "sc_", allcells[i])
  
  seurat <- readRDS(paste0("Saves/Celltype_supercells/", ct, ".RDS")) %>% DietSeurat(counts = TRUE)
  samples_to_remove <- c("XY-TriSeptum-12", "XY-TriSeptum-24", "XY-TriSeptum-2")
  seurat <- subset(seurat, sampleName %in% samples_to_remove, invert = TRUE)
  
  currentsubset <- subset(seurat, Genotype %in% c("XYM","XXF","XXM" ,"XYF"))
  currentsubset@meta.data <- currentsubset@meta.data %>%
    dplyr::mutate(Genotype = factor(Genotype, levels = c("XYM","XXF","XXM" ,"XYF")),
                  SexChrom = factor(SexChrom, levels = c("XY", "XX")),
                  Gonad = factor(Gonad, levels = c("Male", "Female")))
  
  dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  #keep.exprs <- filterByExpr(dge)
  #dge <- dge[keep.exprs,, keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
    
  design <- model.matrix(~Gonad + SexChrom + Gonad:SexChrom, data = currentsubset@meta.data)
    
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  dt1 <- decideTests(fit, method = "separate")
  dt2 <- decideTests(fit, method = "global")
  
  dt_list[["separate"]][[currentcell]] <- dt1
  dt_list[["global"]][[currentcell]] <- dt2
  fit_list[[currentcell]] <- fit 
  
  write.fit(fit, method = "global", adjust = "BH", sep = "\t", quote = FALSE, file = paste0(data.dir, "/Data/Derived/Supercell_DEG/global_fit/fit_results/FCG/", ct, ".txt"))
    
  #resultlist_fcg[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  #resultlist_fcg[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "SexChromXX")
  #resultlist_fcg[["Ovary:SexChromXX"]] <- topTable(fit, n = Inf, coef = "GonadFemale:SexChromXX")
    
  #save(resultlist_fcg, file = paste0("Data/Derived/Pseudobulk_DEG_sum/FCG/", currentcell,".rda"))
}

run_venn(dt_list, "FCG", "~/project-xyang123/medial_septum_sct/Plots/Supercell_DEG/venn/")
summary <- get_summary(dt_list)
summary[[1]]

##process written fit file 
for(i in 1:length(allcells)) {
  
  resultlist_fcg <- list()
  
  sc_count <- "50"
  currentcell <- allcells[i]
  ct <- paste0(sc_count, "sc_", allcells[i])
  
  DEresults <- read.table(paste0(data.dir, "/Data/Derived/Supercell_DEG/global_fit/fit_results/FCG/", ct, ".txt"), sep = "\t", header = TRUE, row.names = 1)
  head(DEresults)
  
  resultlist_fcg[["Ovary_vs_Testis"]] <- DEresults %>% dplyr::select(Coef.GonadFemale, t.GonadFemale, P.value.GonadFemale, P.value.adj.GonadFemale, F, F.p.value)
  resultlist_fcg[["XX_vs_XY"]] <- DEresults %>% dplyr::select(Coef.SexChromXX, t.SexChromXX, P.value.SexChromXX, P.value.adj.SexChromXX, F, F.p.value)
  resultlist_fcg[["Ovary:SexChromXX"]] <- DEresults %>% dplyr::select(Coef.GonadFemale.SexChromXX, t.GonadFemale.SexChromXX, P.value.GonadFemale.SexChromXX, P.value.adj.GonadFemale.SexChromXX, F, F.p.value)
  
  resultlist_fcg <- lapply(resultlist_fcg, setNames, c("logFC", "T", "P.Val", "adj.P.Val", "F", "F.P.Val"))
  
  save(resultlist_fcg, file = paste0(data.dir, "/Data/Derived/Supercell_DEG/global_fit/FCG/", ct,".rda"))
}
```

```{r}
##complete analysis
dt_list <- list()
fit_list <- list()
for (i in 1:length(allcells)) {
  
  sc_count <- "50"
  currentcell <- allcells[i]
  ct <- paste0(sc_count, "sc_", allcells[i])
  
  seurat <- readRDS(paste0("Saves/Celltype_supercells/", ct, ".RDS")) %>% DietSeurat(counts = TRUE)
  samples_to_remove <- c("XY-TriSeptum-12", "XY-TriSeptum-24", "XY-TriSeptum-2")
  seurat <- subset(seurat, sampleName %in% samples_to_remove, invert = TRUE)
  
  seurat$Gonad <- factor(seurat$Gonad, levels = c("Male", "Female"))
  seurat$base_SexChrom <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XY", "XX", "XYY", "XXY"),
                                to = c("XY", "XX", "XY", "XY")) %>% factor(levels = c("XY", "XX"))
  seurat$addX <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XY", "XX", "XYY", "XXY"),
                                       to = c(0, 0, 0, 1)) %>% factor(levels = c(0,1))
  seurat$addY <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XY", "XX", "XYY", "XXY"),
                                       to = c(0, 0, 1, 0)) %>% factor(levels = c(0, 1))
  
  dge0 <- DGEList(seurat@assays$RNA@counts, group = seurat$sampleName)
  dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
  #keep.exprs <- filterByExpr(dge)
  #dge <- dge[keep.exprs,, keep.lib.sizes=FALSE]
  dge <- calcNormFactors(dge)
    
  design <- model.matrix(~Gonad + base_SexChrom + addX + addY, data = seurat@meta.data)
    
  y <- new("EList")
  y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
  fit <- lmFit(y, design = design)
  fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
  dt1 <- decideTests(fit, method = "separate")
  dt2 <- decideTests(fit, method = "global")
  
  dt_list[["separate"]][[currentcell]] <- dt1
  dt_list[["global"]][[currentcell]] <- dt2
  fit_list[[currentcell]] <- fit 
  
  write.fit(fit, method = "global", adjust = "BH", sep = "\t", quote = FALSE, file = paste0(data.dir, "/Data/Derived/Supercell_DEG/global_fit/fit_results/Complete/", ct, ".txt"))
    
  #resultlist_fcg[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
  #resultlist_fcg[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "SexChromXX")
  #resultlist_fcg[["Ovary:SexChromXX"]] <- topTable(fit, n = Inf, coef = "GonadFemale:SexChromXX")
    
  #save(resultlist_fcg, file = paste0("Data/Derived/Pseudobulk_DEG_sum/FCG/", currentcell,".rda"))
}

run_venn(dt_list, "Complete", "~/project-xyang123/medial_septum_sct/Plots/Supercell_DEG/venn/")
summary <- get_summary(dt_list)
summary[[2]]

##process written fit file 
for(i in 1:length(allcells)) {
  
  resultlist_complete <- list()
  
  sc_count <- "50"
  currentcell <- allcells[i]
  ct <- paste0(sc_count, "sc_", allcells[i])
  
  DEresults <- read.table(paste0(data.dir, "/Data/Derived/Supercell_DEG/global_fit/fit_results/Complete/", ct, ".txt"), sep = "\t", header = TRUE, row.names = 1)
  head(DEresults)
  
  resultlist_complete[["Ovary_vs_Testis"]] <- DEresults %>% dplyr::select(Coef.GonadFemale, t.GonadFemale, P.value.GonadFemale, P.value.adj.GonadFemale, F, F.p.value)
  resultlist_complete[["XX_vs_XY"]] <- DEresults %>% dplyr::select(Coef.base_SexChromXX, t.base_SexChromXX, P.value.base_SexChromXX, P.value.adj.base_SexChromXX, F, F.p.value)
  resultlist_complete[["addX"]] <- DEresults %>% dplyr::select(Coef.addX1, t.addX1, P.value.addX1, P.value.adj.addX1, F, F.p.value)
  resultlist_complete[["addY"]] <- DEresults %>% dplyr::select(Coef.addY1, t.addY1, P.value.addY1, P.value.adj.addY1, F, F.p.value)
  
  resultlist_complete <- lapply(resultlist_complete, setNames, c("logFC", "T", "P.Val", "adj.P.Val", "F", "F.P.Val"))
  
  save(resultlist_complete, file = paste0(data.dir, "/Data/Derived/Supercell_DEG/global_fit/Complete/", ct,".rda"))
}
```

PROCESS DEGS  
```{r}
alldata <- list.dirs("~/scratch/old-scratch-julianas/medial_septum_sct/Data/Derived/Supercell_DEG/global_fit", recursive = FALSE)
alldata <- alldata[-c(3)]

topgenes <- list()
DEG_results <- list()

for(i in 1:length(allcells)) {
  currentcell <- as.character(allcells[i])
  sc_count <- "50"
  ct <- paste0(sc_count, "sc_", allcells[i])
  
  for(j in 1:length(alldata)) {
    load(paste0(alldata[j], "/", ct, ".rda"))
  }
  
  ##normative model
  for(k in 1:length(resultlist_normative)) {

    currentframe <- resultlist_normative[[k]]
    if(nrow(currentframe) == 0) {next}
    
    currentframe <- tibble::rownames_to_column(currentframe, "gene")
    if(nrow(currentframe) == 0) {next}
    currentcomparison <- names(resultlist_normative[k])
    currentmodel <- "Normative"
    currentframe$cell_type <- currentcell
    currentframe$model <- currentmodel
    currentframe$comparison <- currentcomparison
    currentframe$supercell <- as.numeric(sc_count)
    currentframe <- currentframe %>% dplyr::arrange(-logFC)

    topgenes[[currentmodel]][[currentcomparison]][[currentcell]] <- currentframe$gene[c(1:min(3,nrow(currentframe)))]
    DEG_results[[currentmodel]][[currentcomparison]][[currentcell]] <- currentframe
  }
  
  ##FCG model 
  for(k in 1:length(resultlist_fcg)) {
 
    currentframe <- resultlist_fcg[[k]]
    if(nrow(currentframe) == 0) {next}
    
    currentframe <- tibble::rownames_to_column(currentframe, "gene")
    if(nrow(currentframe) == 0) {next}
    currentcomparison <- names(resultlist_fcg[k])
    currentmodel <- "FCG"
    currentframe$cell_type <- currentcell
    currentframe$model <- currentmodel
    currentframe$comparison <- currentcomparison
    currentframe$supercell <- as.numeric(sc_count)
    currentframe <- currentframe %>% dplyr::arrange(-logFC)

    topgenes[[currentmodel]][[currentcomparison]][[currentcell]] <- currentframe$gene[c(1:min(3,nrow(currentframe)))]
    DEG_results[[currentmodel]][[currentcomparison]][[currentcell]] <- currentframe
  }
  
  ##Complete model 
  for(k in 1:length(resultlist_complete)) {
 
    currentframe <- resultlist_complete[[k]]
    if(nrow(currentframe) == 0) {next}
    
    currentframe <- tibble::rownames_to_column(currentframe, "gene")
    if(nrow(currentframe) == 0) {next}
    currentcomparison <- names(resultlist_complete[k])
    currentmodel <- "Complete"
    currentframe$cell_type <- currentcell
    currentframe$model <- currentmodel
    currentframe$comparison <- currentcomparison
    currentframe$supercell <- as.numeric(sc_count)
    currentframe <- currentframe %>% dplyr::arrange(-logFC)

    topgenes[[currentmodel]][[currentcomparison]][[currentcell]] <- currentframe$gene[c(1:min(3,nrow(currentframe)))]
    DEG_results[[currentmodel]][[currentcomparison]][[currentcell]] <- currentframe
  }
}

save(topgenes, DEG_results, file = paste0(data.dir, "/Results/Supercell_DEG/DEG_results.Rda"))
```

###################################

##Working with 1 cell type at a time 

```{r}
##Load in files
i = 1
allcells <- c("Neuron", "Astrocyte", "Oligodendrocyte Progenitor Cell", "Microglia", "Myelinating Oligodendrocyte", "Endothelial", "Ependymal", "Intermediate Progenitor Cell")
allcells <- gsub(" ", "_", allcells)
ct <- paste0("50sc_", allcells[i])

seurat <- readRDS(paste0("Saves/Celltype_supercells/", ct, ".RDS")) %>% DietSeurat(counts = TRUE)

samples_to_remove <- c("XY-TriSeptum-12", "XY-TriSeptum-24", "XY-TriSeptum-2")
seurat <- subset(seurat, sampleName %in% samples_to_remove, invert = TRUE)
```

```{r, eval = FALSE}
##Edit metadata 
seurat$Xdose <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(2, 2, 1 ,1)) %>% factor(levels = c(1, 2))
seurat$Xdose_cont <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(2, 2, 1 ,1)) %>% as.character() %>% as.numeric()
seurat$Ydose <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 1 ,2)) %>% factor(levels = c(0, 1, 2))
seurat$Ydose_cont <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c(0, 1, 1 ,2)) %>% as.character() %>% as.numeric()
seurat$base_SexChrom <- plyr::mapvalues(seurat$SexChrom,
                                from = c("XX", "XXY", "XY", "XYY"),
                                to = c("XX", "XY", "XY", "XY")) %>% factor(levels = c("XY", "XX"))

##previous analysis
seurat$addX <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XY", "XXY"),
                                       to = c(0, 1)) %>% factor(levels = c(0,1))

seurat$addY <- plyr::mapvalues(seurat$SexChrom,
                                       from = c("XX", "XXY", "XY", "XYY"),
                                       to = c(0, 1, 0, 2)) %>% factor(levels = c(0, 1, 2))

seurat$Gonad <- factor(seurat$Gonad, levels = c("Male", "Female"))
seurat$SexChrom <- factor(seurat$SexChrom, levels = c("XY", "XX", "XYY", "XXY"))
seurat$Genotype <- factor(seurat$Genotype, levels = c("XYM", "XYF", "XXM", "XXF", "XYYM", "XYYF", "XXYM", "XXYF"))
seurat$Trisomy <- factor(seurat$Trisomy, levels = c("Trisomy", "Non-Trisomy"))
```

###################################

LINEAR MODELING WITH LIMMA 

```{r}
##normative analysis (XYM vs XXM) 

resultlist_normative <- list()
  
dge0 <- DGEList(seurat@assays$RNA@counts, group = seurat$sampleName)
dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
#keep.exprs <- filterByExpr(dge0)
#x <- x[keep.exprs,, keep.lib.sizes=FALSE]
dge <- calcNormFactors(dge)
  
design <- model.matrix(~0 + Genotype, data = seurat@meta.data)
  
y <- new("EList")
y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
fit <- lmFit(y, design = design)
#contrasts <- makeContrasts(XXF_vs_XYM = GenotypeXXF - GenotypeXYM,
#                           levels = design)
fit <- contrasts.fit(fit, contrasts)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)

dt1 <- decideTests(fit, method = "separate")
dt2 <- decideTests(fit, method = "global")
  
resultlist_normative[["XXF_vs_XYM"]] <- topTable(fit, n = Inf, coef = "XXF_vs_XYM")

save(resultlist_normative, file = paste0("Data/Derived/Supercell_DEG/normative/", ct,".rda"))
```

```{r}
##sexchrom and gonad analysis (FCG)

resultlist_fcg <- list()
  
currentsubset <- subset(seurat, Genotype %in% c("XYM","XXF","XXM" ,"XYF"))
currentsubset@meta.data <- currentsubset@meta.data %>%
  dplyr::mutate(Genotype = factor(Genotype, levels = c("XYM","XXF","XXM" ,"XYF")),
                SexChrom = factor(SexChrom, levels = c("XY", "XX")),
                Gonad = factor(Gonad, levels = c("Male", "Female")))
  gc()
  
dge0 <- DGEList(currentsubset@assays$RNA@counts, group = currentsubset$sampleName)
dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
keep.exprs <- filterByExpr(dge)
dge <- dge[keep.exprs,, keep.lib.sizes=FALSE]
dge <- calcNormFactors(dge)
  
design <- model.matrix(~Gonad + SexChrom + Gonad:SexChrom, data = currentsubset@meta.data)
  
y <- new("EList")
y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
fit <- lmFit(y, design = design)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)

dt1 <- decideTests(fit, method = "separate")
dt2 <- decideTests(fit, method = "global")
  
resultlist_fcg[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
resultlist_fcg[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "SexChromXX")
resultlist_fcg[["Ovary:SexChromXX"]] <- topTable(fit, n = Inf, coef = "GonadFemale:SexChromXX")
  
save(resultlist_fcg, file = paste0("Data/Derived/Supercell_DEG/FCG/", ct,".rda"))

```

```{r}
##full model (X and Y dose + gonad)

resultlist_dose <- list()
  
dge0 <- DGEList(seurat@assays$RNA@counts, group = seurat$sampleName)
dge <- dge0[!rowSums(dge0$counts==0)==ncol(dge0$counts), ]
#keep.exprs <- filterByExpr(dge0)
#x <- x[keep.exprs,, keep.lib.sizes=FALSE]
dge <- calcNormFactors(dge)
  
design <- model.matrix(~Gonad + Xdose_cont + Ydose_cont, data = seurat@meta.data)
  
y <- new("EList")
y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
fit <- lmFit(y, design = design)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
resultlist_dose[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
resultlist_dose[["Xdose"]] <- topTable(fit, n = Inf, coef = "Xdose_cont")
resultlist_dose[["Ydose"]] <- topTable(fit, n = Inf, coef = "Ydose_cont")
#resultlist_dose[["Ovary:Xdose"]] <- topTable(fit, n = Inf, coef = "GonadFemale.Xdose_cont")
#resultlist_dose[["Ovary:Ydose"]] <- topTable(fit, n = Inf, coef = "GonadFemale.Ydose_cont")
#resultlist_dose[["Xdose:Ydose"]] <- topTable(fit, n = Inf, coef = "Xdose_cont.Ydose_cont")

save(resultlist_dose, file = paste0("Data/Derived/Supercell_DEG/Dose/", ct,".rda"))
```

```{r}
##quadratic full model

resultlist_quad <- list()

design <- model.matrix(~Gonad + Xdose_cont + poly(Ydose_cont, degree=2), data=seurat@meta.data)

y <- new("EList")
y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
fit <- lmFit(y, design = design)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
resultlist_quad[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
resultlist_quad[["Xdose"]] <- topTable(fit, n = Inf, coef = "Xdose_cont")
resultlist_quad[["Ydose"]] <- topTable(fit, n = Inf, coef = "poly(Ydose_cont, degree = 2)1")
resultlist_quad[["Ydose^2"]] <- topTable(fit, n = Inf, coef = "poly(Ydose_cont, degree = 2)2")

save(resultlist_quad, file = paste0("Data/Derived/Supercell_DEG/Quadratic/", ct,".rda"))
```

```{r}
##Aneuploidy model
 
resultlist_aneuploidy <- list()
 
design <- model.matrix(~Gonad + base_SexChrom + Trisomy + Gonad:base_SexChrom + Gonad:Trisomy + base_SexChrom:Trisomy, data = seurat@meta.data) 

y <- new("EList")
y$E <- edgeR::cpm(dge, log = TRUE, prior.count = 3) 
fit <- lmFit(y, design = design)
fit <- eBayes(fit, trend = TRUE, robust = TRUE)
  
resultlist_aneuploidy[["Ovary_vs_Testis"]] <- topTable(fit, n = Inf, coef = "GonadFemale")
resultlist_aneuploidy[["XX_vs_XY"]] <- topTable(fit, n = Inf, coef = "base_SexChromXX")
resultlist_aneuploidy[["Aneuploidy"]] <- topTable(fit, n = Inf, coef = "TrisomyNon-Trisomy")
resultlist_aneuploidy[["Ovary:SexChromXX"]] <- topTable(fit, n = Inf, coef = "GonadFemale:base_SexChromXX")
resultlist_aneuploidy[["Ovary:Aneuploidy"]] <- topTable(fit, n = Inf, coef = "GonadFemale:TrisomyNon-Trisomy")
resultlist_aneuploidy[["SexChromXX:Aneuploidy"]] <- topTable(fit, n = Inf, coef = "base_SexChromXX:TrisomyNon-Trisomy")

save(resultlist_aneuploidy, file = paste0("Data/Derived/Supercell_DEG/Aneuploidy/", ct,".rda"))
```